// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: tickets/tickets.proto

package tickets

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	api "partivo_tickets/api"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TicketsService_GetEventTickets_FullMethodName   = "/api.tickets.TicketsService/GetEventTickets"
	TicketsService_GetSessionTickets_FullMethodName = "/api.tickets.TicketsService/GetSessionTickets"
)

// TicketsServiceClient is the client API for TicketsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TicketsServiceClient interface {
	GetEventTickets(ctx context.Context, in *GetEventTicketTypesRequest, opts ...grpc.CallOption) (*api.Response, error)
	GetSessionTickets(ctx context.Context, in *GetSessionTicketsRequest, opts ...grpc.CallOption) (*api.Response, error)
}

type ticketsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketsServiceClient(cc grpc.ClientConnInterface) TicketsServiceClient {
	return &ticketsServiceClient{cc}
}

func (c *ticketsServiceClient) GetEventTickets(ctx context.Context, in *GetEventTicketTypesRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, TicketsService_GetEventTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketsServiceClient) GetSessionTickets(ctx context.Context, in *GetSessionTicketsRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, TicketsService_GetSessionTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketsServiceServer is the server API for TicketsService service.
// All implementations must embed UnimplementedTicketsServiceServer
// for forward compatibility.
type TicketsServiceServer interface {
	GetEventTickets(context.Context, *GetEventTicketTypesRequest) (*api.Response, error)
	GetSessionTickets(context.Context, *GetSessionTicketsRequest) (*api.Response, error)
	mustEmbedUnimplementedTicketsServiceServer()
}

// UnimplementedTicketsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTicketsServiceServer struct{}

func (UnimplementedTicketsServiceServer) GetEventTickets(context.Context, *GetEventTicketTypesRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventTickets not implemented")
}
func (UnimplementedTicketsServiceServer) GetSessionTickets(context.Context, *GetSessionTicketsRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionTickets not implemented")
}
func (UnimplementedTicketsServiceServer) mustEmbedUnimplementedTicketsServiceServer() {}
func (UnimplementedTicketsServiceServer) testEmbeddedByValue()                        {}

// UnsafeTicketsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketsServiceServer will
// result in compilation errors.
type UnsafeTicketsServiceServer interface {
	mustEmbedUnimplementedTicketsServiceServer()
}

func RegisterTicketsServiceServer(s grpc.ServiceRegistrar, srv TicketsServiceServer) {
	// If the following call pancis, it indicates UnimplementedTicketsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TicketsService_ServiceDesc, srv)
}

func _TicketsService_GetEventTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventTicketTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketsServiceServer).GetEventTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketsService_GetEventTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketsServiceServer).GetEventTickets(ctx, req.(*GetEventTicketTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketsService_GetSessionTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketsServiceServer).GetSessionTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketsService_GetSessionTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketsServiceServer).GetSessionTickets(ctx, req.(*GetSessionTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TicketsService_ServiceDesc is the grpc.ServiceDesc for TicketsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicketsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.tickets.TicketsService",
	HandlerType: (*TicketsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEventTickets",
			Handler:    _TicketsService_GetEventTickets_Handler,
		},
		{
			MethodName: "GetSessionTickets",
			Handler:    _TicketsService_GetSessionTickets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tickets/tickets.proto",
}

const (
	TicketsAdminService_CheckInTicket_FullMethodName          = "/api.tickets.TicketsAdminService/CheckInTicket"
	TicketsAdminService_AddTicketType_FullMethodName          = "/api.tickets.TicketsAdminService/AddTicketType"
	TicketsAdminService_GetEventTicketTypes_FullMethodName    = "/api.tickets.TicketsAdminService/GetEventTicketTypes"
	TicketsAdminService_DeleteTicketType_FullMethodName       = "/api.tickets.TicketsAdminService/DeleteTicketType"
	TicketsAdminService_UpdateTicketType_FullMethodName       = "/api.tickets.TicketsAdminService/UpdateTicketType"
	TicketsAdminService_UpdateTicketTypesOrder_FullMethodName = "/api.tickets.TicketsAdminService/UpdateTicketTypesOrder"
)

// TicketsAdminServiceClient is the client API for TicketsAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TicketsAdminServiceClient interface {
	CheckInTicket(ctx context.Context, in *CheckInTicketRequest, opts ...grpc.CallOption) (*api.Response, error)
	AddTicketType(ctx context.Context, in *AddTicketTypeRequest, opts ...grpc.CallOption) (*api.Response, error)
	GetEventTicketTypes(ctx context.Context, in *GetEventTicketTypesRequest, opts ...grpc.CallOption) (*api.Response, error)
	DeleteTicketType(ctx context.Context, in *DeleteTicketTypeRequest, opts ...grpc.CallOption) (*api.Response, error)
	UpdateTicketType(ctx context.Context, in *UpdateTicketTypeRequest, opts ...grpc.CallOption) (*api.Response, error)
	UpdateTicketTypesOrder(ctx context.Context, in *UpdateTicketTypesOrderRequest, opts ...grpc.CallOption) (*api.Response, error)
}

type ticketsAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketsAdminServiceClient(cc grpc.ClientConnInterface) TicketsAdminServiceClient {
	return &ticketsAdminServiceClient{cc}
}

func (c *ticketsAdminServiceClient) CheckInTicket(ctx context.Context, in *CheckInTicketRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, TicketsAdminService_CheckInTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketsAdminServiceClient) AddTicketType(ctx context.Context, in *AddTicketTypeRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, TicketsAdminService_AddTicketType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketsAdminServiceClient) GetEventTicketTypes(ctx context.Context, in *GetEventTicketTypesRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, TicketsAdminService_GetEventTicketTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketsAdminServiceClient) DeleteTicketType(ctx context.Context, in *DeleteTicketTypeRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, TicketsAdminService_DeleteTicketType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketsAdminServiceClient) UpdateTicketType(ctx context.Context, in *UpdateTicketTypeRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, TicketsAdminService_UpdateTicketType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketsAdminServiceClient) UpdateTicketTypesOrder(ctx context.Context, in *UpdateTicketTypesOrderRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, TicketsAdminService_UpdateTicketTypesOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketsAdminServiceServer is the server API for TicketsAdminService service.
// All implementations must embed UnimplementedTicketsAdminServiceServer
// for forward compatibility.
type TicketsAdminServiceServer interface {
	CheckInTicket(context.Context, *CheckInTicketRequest) (*api.Response, error)
	AddTicketType(context.Context, *AddTicketTypeRequest) (*api.Response, error)
	GetEventTicketTypes(context.Context, *GetEventTicketTypesRequest) (*api.Response, error)
	DeleteTicketType(context.Context, *DeleteTicketTypeRequest) (*api.Response, error)
	UpdateTicketType(context.Context, *UpdateTicketTypeRequest) (*api.Response, error)
	UpdateTicketTypesOrder(context.Context, *UpdateTicketTypesOrderRequest) (*api.Response, error)
	mustEmbedUnimplementedTicketsAdminServiceServer()
}

// UnimplementedTicketsAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTicketsAdminServiceServer struct{}

func (UnimplementedTicketsAdminServiceServer) CheckInTicket(context.Context, *CheckInTicketRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckInTicket not implemented")
}
func (UnimplementedTicketsAdminServiceServer) AddTicketType(context.Context, *AddTicketTypeRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTicketType not implemented")
}
func (UnimplementedTicketsAdminServiceServer) GetEventTicketTypes(context.Context, *GetEventTicketTypesRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventTicketTypes not implemented")
}
func (UnimplementedTicketsAdminServiceServer) DeleteTicketType(context.Context, *DeleteTicketTypeRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTicketType not implemented")
}
func (UnimplementedTicketsAdminServiceServer) UpdateTicketType(context.Context, *UpdateTicketTypeRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTicketType not implemented")
}
func (UnimplementedTicketsAdminServiceServer) UpdateTicketTypesOrder(context.Context, *UpdateTicketTypesOrderRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTicketTypesOrder not implemented")
}
func (UnimplementedTicketsAdminServiceServer) mustEmbedUnimplementedTicketsAdminServiceServer() {}
func (UnimplementedTicketsAdminServiceServer) testEmbeddedByValue()                             {}

// UnsafeTicketsAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketsAdminServiceServer will
// result in compilation errors.
type UnsafeTicketsAdminServiceServer interface {
	mustEmbedUnimplementedTicketsAdminServiceServer()
}

func RegisterTicketsAdminServiceServer(s grpc.ServiceRegistrar, srv TicketsAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedTicketsAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TicketsAdminService_ServiceDesc, srv)
}

func _TicketsAdminService_CheckInTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketsAdminServiceServer).CheckInTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketsAdminService_CheckInTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketsAdminServiceServer).CheckInTicket(ctx, req.(*CheckInTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketsAdminService_AddTicketType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTicketTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketsAdminServiceServer).AddTicketType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketsAdminService_AddTicketType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketsAdminServiceServer).AddTicketType(ctx, req.(*AddTicketTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketsAdminService_GetEventTicketTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventTicketTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketsAdminServiceServer).GetEventTicketTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketsAdminService_GetEventTicketTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketsAdminServiceServer).GetEventTicketTypes(ctx, req.(*GetEventTicketTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketsAdminService_DeleteTicketType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTicketTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketsAdminServiceServer).DeleteTicketType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketsAdminService_DeleteTicketType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketsAdminServiceServer).DeleteTicketType(ctx, req.(*DeleteTicketTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketsAdminService_UpdateTicketType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketsAdminServiceServer).UpdateTicketType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketsAdminService_UpdateTicketType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketsAdminServiceServer).UpdateTicketType(ctx, req.(*UpdateTicketTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketsAdminService_UpdateTicketTypesOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketTypesOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketsAdminServiceServer).UpdateTicketTypesOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketsAdminService_UpdateTicketTypesOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketsAdminServiceServer).UpdateTicketTypesOrder(ctx, req.(*UpdateTicketTypesOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TicketsAdminService_ServiceDesc is the grpc.ServiceDesc for TicketsAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicketsAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.tickets.TicketsAdminService",
	HandlerType: (*TicketsAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckInTicket",
			Handler:    _TicketsAdminService_CheckInTicket_Handler,
		},
		{
			MethodName: "AddTicketType",
			Handler:    _TicketsAdminService_AddTicketType_Handler,
		},
		{
			MethodName: "GetEventTicketTypes",
			Handler:    _TicketsAdminService_GetEventTicketTypes_Handler,
		},
		{
			MethodName: "DeleteTicketType",
			Handler:    _TicketsAdminService_DeleteTicketType_Handler,
		},
		{
			MethodName: "UpdateTicketType",
			Handler:    _TicketsAdminService_UpdateTicketType_Handler,
		},
		{
			MethodName: "UpdateTicketTypesOrder",
			Handler:    _TicketsAdminService_UpdateTicketTypesOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tickets/tickets.proto",
}
