// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: tickets/tickets.proto

package tickets

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	api "partivo_tickets/api"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddTicketTypeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repeated string session = 1 [(buf.validate.field).repeated = {min_items: 1,
	//
	//	unique:true,
	//	items: {
	//	  string: {
	//	    len: 24
	//	  }
	//	}}];
	Name                string                          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity            uint32                          `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price               string                          `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Desc                string                          `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Sessions            []*AddTicketTypeRequest_Session `protobuf:"bytes,6,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Visibility          bool                            `protobuf:"varint,10,opt,name=visibility,proto3" json:"visibility,omitempty"`
	StartShowingOn      *timestamppb.Timestamp          `protobuf:"bytes,8,opt,name=start_showing_on,json=startShowingOn,proto3,oneof" json:"start_showing_on,omitempty"`
	StopShowingOn       *timestamppb.Timestamp          `protobuf:"bytes,9,opt,name=stop_showing_on,json=stopShowingOn,proto3,oneof" json:"stop_showing_on,omitempty"`
	Pick                uint32                          `protobuf:"varint,11,opt,name=pick,proto3" json:"pick,omitempty"`
	MinQuantityPerOrder uint32                          `protobuf:"varint,12,opt,name=min_quantity_per_order,json=minQuantityPerOrder,proto3" json:"min_quantity_per_order,omitempty"`
	MaxQuantityPerOrder uint32                          `protobuf:"varint,13,opt,name=max_quantity_per_order,json=maxQuantityPerOrder,proto3" json:"max_quantity_per_order,omitempty"`
	DueDuration         *durationpb.Duration            `protobuf:"bytes,14,opt,name=due_duration,json=dueDuration,proto3,oneof" json:"due_duration,omitempty"`
	Event               string                          `protobuf:"bytes,15,opt,name=event,proto3" json:"event,omitempty"`
	Enable              bool                            `protobuf:"varint,16,opt,name=enable,proto3" json:"enable,omitempty"`
	SaleTimeSetting     string                          `protobuf:"bytes,7,opt,name=sale_time_setting,json=saleTimeSetting,proto3" json:"sale_time_setting,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AddTicketTypeRequest) Reset() {
	*x = AddTicketTypeRequest{}
	mi := &file_tickets_tickets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTicketTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTicketTypeRequest) ProtoMessage() {}

func (x *AddTicketTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTicketTypeRequest.ProtoReflect.Descriptor instead.
func (*AddTicketTypeRequest) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{0}
}

func (x *AddTicketTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddTicketTypeRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddTicketTypeRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *AddTicketTypeRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *AddTicketTypeRequest) GetSessions() []*AddTicketTypeRequest_Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *AddTicketTypeRequest) GetVisibility() bool {
	if x != nil {
		return x.Visibility
	}
	return false
}

func (x *AddTicketTypeRequest) GetStartShowingOn() *timestamppb.Timestamp {
	if x != nil {
		return x.StartShowingOn
	}
	return nil
}

func (x *AddTicketTypeRequest) GetStopShowingOn() *timestamppb.Timestamp {
	if x != nil {
		return x.StopShowingOn
	}
	return nil
}

func (x *AddTicketTypeRequest) GetPick() uint32 {
	if x != nil {
		return x.Pick
	}
	return 0
}

func (x *AddTicketTypeRequest) GetMinQuantityPerOrder() uint32 {
	if x != nil {
		return x.MinQuantityPerOrder
	}
	return 0
}

func (x *AddTicketTypeRequest) GetMaxQuantityPerOrder() uint32 {
	if x != nil {
		return x.MaxQuantityPerOrder
	}
	return 0
}

func (x *AddTicketTypeRequest) GetDueDuration() *durationpb.Duration {
	if x != nil {
		return x.DueDuration
	}
	return nil
}

func (x *AddTicketTypeRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *AddTicketTypeRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *AddTicketTypeRequest) GetSaleTimeSetting() string {
	if x != nil {
		return x.SaleTimeSetting
	}
	return ""
}

type GetEventTicketTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventTicketTypesRequest) Reset() {
	*x = GetEventTicketTypesRequest{}
	mi := &file_tickets_tickets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventTicketTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventTicketTypesRequest) ProtoMessage() {}

func (x *GetEventTicketTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventTicketTypesRequest.ProtoReflect.Descriptor instead.
func (*GetEventTicketTypesRequest) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{1}
}

func (x *GetEventTicketTypesRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type GetEventTicketTypesResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Data          []*GetEventTicketTypesResponse_Ticket `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventTicketTypesResponse) Reset() {
	*x = GetEventTicketTypesResponse{}
	mi := &file_tickets_tickets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventTicketTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventTicketTypesResponse) ProtoMessage() {}

func (x *GetEventTicketTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventTicketTypesResponse.ProtoReflect.Descriptor instead.
func (*GetEventTicketTypesResponse) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventTicketTypesResponse) GetData() []*GetEventTicketTypesResponse_Ticket {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteTicketTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        string                 `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTicketTypeRequest) Reset() {
	*x = DeleteTicketTypeRequest{}
	mi := &file_tickets_tickets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTicketTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTicketTypeRequest) ProtoMessage() {}

func (x *DeleteTicketTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTicketTypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteTicketTypeRequest) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTicketTypeRequest) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

type UpdateTicketTypeRequest struct {
	state               protoimpl.MessageState             `protogen:"open.v1"`
	Ticket              string                             `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Name                string                             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity            uint32                             `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price               string                             `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Desc                string                             `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	SaleStartAt         *timestamppb.Timestamp             `protobuf:"bytes,6,opt,name=sale_start_at,json=saleStartAt,proto3" json:"sale_start_at,omitempty"`
	SaleEndAt           *timestamppb.Timestamp             `protobuf:"bytes,7,opt,name=sale_end_at,json=saleEndAt,proto3" json:"sale_end_at,omitempty"`
	Visibility          bool                               `protobuf:"varint,8,opt,name=visibility,proto3" json:"visibility,omitempty"`
	StartShowingOn      *timestamppb.Timestamp             `protobuf:"bytes,9,opt,name=start_showing_on,json=startShowingOn,proto3,oneof" json:"start_showing_on,omitempty"`
	StopShowingOn       *timestamppb.Timestamp             `protobuf:"bytes,10,opt,name=stop_showing_on,json=stopShowingOn,proto3,oneof" json:"stop_showing_on,omitempty"`
	MinQuantityPerOrder uint32                             `protobuf:"varint,11,opt,name=min_quantity_per_order,json=minQuantityPerOrder,proto3" json:"min_quantity_per_order,omitempty"`
	MaxQuantityPerOrder uint32                             `protobuf:"varint,12,opt,name=max_quantity_per_order,json=maxQuantityPerOrder,proto3" json:"max_quantity_per_order,omitempty"`
	DueDuration         *durationpb.Duration               `protobuf:"bytes,13,opt,name=due_duration,json=dueDuration,proto3,oneof" json:"due_duration,omitempty"`
	SaleTimeSetting     string                             `protobuf:"bytes,14,opt,name=sale_time_setting,json=saleTimeSetting,proto3" json:"sale_time_setting,omitempty"`
	Sessions            []*UpdateTicketTypeRequest_Session `protobuf:"bytes,15,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Enable              bool                               `protobuf:"varint,16,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateTicketTypeRequest) Reset() {
	*x = UpdateTicketTypeRequest{}
	mi := &file_tickets_tickets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketTypeRequest) ProtoMessage() {}

func (x *UpdateTicketTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketTypeRequest) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTicketTypeRequest) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *UpdateTicketTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTicketTypeRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateTicketTypeRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *UpdateTicketTypeRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UpdateTicketTypeRequest) GetSaleStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleStartAt
	}
	return nil
}

func (x *UpdateTicketTypeRequest) GetSaleEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleEndAt
	}
	return nil
}

func (x *UpdateTicketTypeRequest) GetVisibility() bool {
	if x != nil {
		return x.Visibility
	}
	return false
}

func (x *UpdateTicketTypeRequest) GetStartShowingOn() *timestamppb.Timestamp {
	if x != nil {
		return x.StartShowingOn
	}
	return nil
}

func (x *UpdateTicketTypeRequest) GetStopShowingOn() *timestamppb.Timestamp {
	if x != nil {
		return x.StopShowingOn
	}
	return nil
}

func (x *UpdateTicketTypeRequest) GetMinQuantityPerOrder() uint32 {
	if x != nil {
		return x.MinQuantityPerOrder
	}
	return 0
}

func (x *UpdateTicketTypeRequest) GetMaxQuantityPerOrder() uint32 {
	if x != nil {
		return x.MaxQuantityPerOrder
	}
	return 0
}

func (x *UpdateTicketTypeRequest) GetDueDuration() *durationpb.Duration {
	if x != nil {
		return x.DueDuration
	}
	return nil
}

func (x *UpdateTicketTypeRequest) GetSaleTimeSetting() string {
	if x != nil {
		return x.SaleTimeSetting
	}
	return ""
}

func (x *UpdateTicketTypeRequest) GetSessions() []*UpdateTicketTypeRequest_Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *UpdateTicketTypeRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type UpdateTicketTypesOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Order         []string               `protobuf:"bytes,2,rep,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketTypesOrderRequest) Reset() {
	*x = UpdateTicketTypesOrderRequest{}
	mi := &file_tickets_tickets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketTypesOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketTypesOrderRequest) ProtoMessage() {}

func (x *UpdateTicketTypesOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketTypesOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketTypesOrderRequest) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTicketTypesOrderRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *UpdateTicketTypesOrderRequest) GetOrder() []string {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetSessionTicketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionTicketsRequest) Reset() {
	*x = GetSessionTicketsRequest{}
	mi := &file_tickets_tickets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionTicketsRequest) ProtoMessage() {}

func (x *GetSessionTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionTicketsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionTicketsRequest) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionTicketsRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type GetSessionTicketsResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Data          []*GetSessionTicketsResponse_Ticket `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionTicketsResponse) Reset() {
	*x = GetSessionTicketsResponse{}
	mi := &file_tickets_tickets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionTicketsResponse) ProtoMessage() {}

func (x *GetSessionTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionTicketsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionTicketsResponse) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{7}
}

func (x *GetSessionTicketsResponse) GetData() []*GetSessionTicketsResponse_Ticket {
	if x != nil {
		return x.Data
	}
	return nil
}

type CheckInTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QrCode        string                 `protobuf:"bytes,1,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInTicketRequest) Reset() {
	*x = CheckInTicketRequest{}
	mi := &file_tickets_tickets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInTicketRequest) ProtoMessage() {}

func (x *CheckInTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInTicketRequest.ProtoReflect.Descriptor instead.
func (*CheckInTicketRequest) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{8}
}

func (x *CheckInTicketRequest) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

type CheckInTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UsedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=used_at,json=usedAt,proto3" json:"used_at,omitempty"`
	Customer      *api.User              `protobuf:"bytes,4,opt,name=customer,proto3" json:"customer,omitempty"`
	OrderItemName string                 `protobuf:"bytes,5,opt,name=order_item_name,json=orderItemName,proto3" json:"order_item_name,omitempty"`
	CheckedInNow  bool                   `protobuf:"varint,6,opt,name=checked_in_now,json=checkedInNow,proto3" json:"checked_in_now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInTicketResponse) Reset() {
	*x = CheckInTicketResponse{}
	mi := &file_tickets_tickets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInTicketResponse) ProtoMessage() {}

func (x *CheckInTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInTicketResponse.ProtoReflect.Descriptor instead.
func (*CheckInTicketResponse) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{9}
}

func (x *CheckInTicketResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *CheckInTicketResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckInTicketResponse) GetUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UsedAt
	}
	return nil
}

func (x *CheckInTicketResponse) GetCustomer() *api.User {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *CheckInTicketResponse) GetOrderItemName() string {
	if x != nil {
		return x.OrderItemName
	}
	return ""
}

func (x *CheckInTicketResponse) GetCheckedInNow() bool {
	if x != nil {
		return x.CheckedInNow
	}
	return false
}

type AddTicketTypeRequest_Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	SaleStartAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sale_start_at,json=saleStartAt,proto3" json:"sale_start_at,omitempty"`
	SaleEndAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=sale_end_at,json=saleEndAt,proto3" json:"sale_end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTicketTypeRequest_Session) Reset() {
	*x = AddTicketTypeRequest_Session{}
	mi := &file_tickets_tickets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTicketTypeRequest_Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTicketTypeRequest_Session) ProtoMessage() {}

func (x *AddTicketTypeRequest_Session) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTicketTypeRequest_Session.ProtoReflect.Descriptor instead.
func (*AddTicketTypeRequest_Session) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AddTicketTypeRequest_Session) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *AddTicketTypeRequest_Session) GetSaleStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleStartAt
	}
	return nil
}

func (x *AddTicketTypeRequest_Session) GetSaleEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleEndAt
	}
	return nil
}

type GetEventTicketTypesResponse_Ticket struct {
	state               protoimpl.MessageState                            `protogen:"open.v1"`
	Id                  string                                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                                            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity            uint32                                            `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price               string                                            `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Desc                string                                            `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Visibility          bool                                              `protobuf:"varint,8,opt,name=visibility,proto3" json:"visibility,omitempty"`
	StartShowingOn      *timestamppb.Timestamp                            `protobuf:"bytes,9,opt,name=start_showing_on,json=startShowingOn,proto3" json:"start_showing_on,omitempty"`
	StopShowingOn       *timestamppb.Timestamp                            `protobuf:"bytes,10,opt,name=stop_showing_on,json=stopShowingOn,proto3" json:"stop_showing_on,omitempty"`
	CreatedAt           *timestamppb.Timestamp                            `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp                            `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy           *api.User                                         `protobuf:"bytes,13,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy           *api.User                                         `protobuf:"bytes,14,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Pick                uint32                                            `protobuf:"varint,15,opt,name=pick,proto3" json:"pick,omitempty"`
	MinQuantityPerOrder uint32                                            `protobuf:"varint,16,opt,name=min_quantity_per_order,json=minQuantityPerOrder,proto3" json:"min_quantity_per_order,omitempty"`
	MaxQuantityPerOrder uint32                                            `protobuf:"varint,17,opt,name=max_quantity_per_order,json=maxQuantityPerOrder,proto3" json:"max_quantity_per_order,omitempty"`
	SessionsInfo        []*GetEventTicketTypesResponse_Ticket_SessionInfo `protobuf:"bytes,18,rep,name=sessions_info,json=sessionsInfo,proto3" json:"sessions_info,omitempty"`
	Enable              bool                                              `protobuf:"varint,19,opt,name=enable,proto3" json:"enable,omitempty"`
	SaleTimeSetting     string                                            `protobuf:"bytes,20,opt,name=sale_time_setting,json=saleTimeSetting,proto3" json:"sale_time_setting,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetEventTicketTypesResponse_Ticket) Reset() {
	*x = GetEventTicketTypesResponse_Ticket{}
	mi := &file_tickets_tickets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventTicketTypesResponse_Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventTicketTypesResponse_Ticket) ProtoMessage() {}

func (x *GetEventTicketTypesResponse_Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventTicketTypesResponse_Ticket.ProtoReflect.Descriptor instead.
func (*GetEventTicketTypesResponse_Ticket) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetEventTicketTypesResponse_Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetEventTicketTypesResponse_Ticket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetEventTicketTypesResponse_Ticket) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GetEventTicketTypesResponse_Ticket) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetEventTicketTypesResponse_Ticket) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *GetEventTicketTypesResponse_Ticket) GetVisibility() bool {
	if x != nil {
		return x.Visibility
	}
	return false
}

func (x *GetEventTicketTypesResponse_Ticket) GetStartShowingOn() *timestamppb.Timestamp {
	if x != nil {
		return x.StartShowingOn
	}
	return nil
}

func (x *GetEventTicketTypesResponse_Ticket) GetStopShowingOn() *timestamppb.Timestamp {
	if x != nil {
		return x.StopShowingOn
	}
	return nil
}

func (x *GetEventTicketTypesResponse_Ticket) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetEventTicketTypesResponse_Ticket) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetEventTicketTypesResponse_Ticket) GetCreatedBy() *api.User {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *GetEventTicketTypesResponse_Ticket) GetUpdatedBy() *api.User {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

func (x *GetEventTicketTypesResponse_Ticket) GetPick() uint32 {
	if x != nil {
		return x.Pick
	}
	return 0
}

func (x *GetEventTicketTypesResponse_Ticket) GetMinQuantityPerOrder() uint32 {
	if x != nil {
		return x.MinQuantityPerOrder
	}
	return 0
}

func (x *GetEventTicketTypesResponse_Ticket) GetMaxQuantityPerOrder() uint32 {
	if x != nil {
		return x.MaxQuantityPerOrder
	}
	return 0
}

func (x *GetEventTicketTypesResponse_Ticket) GetSessionsInfo() []*GetEventTicketTypesResponse_Ticket_SessionInfo {
	if x != nil {
		return x.SessionsInfo
	}
	return nil
}

func (x *GetEventTicketTypesResponse_Ticket) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *GetEventTicketTypesResponse_Ticket) GetSaleTimeSetting() string {
	if x != nil {
		return x.SaleTimeSetting
	}
	return ""
}

type GetEventTicketTypesResponse_Ticket_SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventTicketTypesResponse_Ticket_SessionInfo) Reset() {
	*x = GetEventTicketTypesResponse_Ticket_SessionInfo{}
	mi := &file_tickets_tickets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventTicketTypesResponse_Ticket_SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventTicketTypesResponse_Ticket_SessionInfo) ProtoMessage() {}

func (x *GetEventTicketTypesResponse_Ticket_SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventTicketTypesResponse_Ticket_SessionInfo.ProtoReflect.Descriptor instead.
func (*GetEventTicketTypesResponse_Ticket_SessionInfo) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *GetEventTicketTypesResponse_Ticket_SessionInfo) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *GetEventTicketTypesResponse_Ticket_SessionInfo) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateTicketTypeRequest_Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	SaleStartAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sale_start_at,json=saleStartAt,proto3" json:"sale_start_at,omitempty"`
	SaleEndAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=sale_end_at,json=saleEndAt,proto3" json:"sale_end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketTypeRequest_Session) Reset() {
	*x = UpdateTicketTypeRequest_Session{}
	mi := &file_tickets_tickets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketTypeRequest_Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketTypeRequest_Session) ProtoMessage() {}

func (x *UpdateTicketTypeRequest_Session) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketTypeRequest_Session.ProtoReflect.Descriptor instead.
func (*UpdateTicketTypeRequest_Session) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UpdateTicketTypeRequest_Session) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *UpdateTicketTypeRequest_Session) GetSaleStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleStartAt
	}
	return nil
}

func (x *UpdateTicketTypeRequest_Session) GetSaleEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleEndAt
	}
	return nil
}

type GetSessionTicketsResponse_Ticket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TotalQuantity uint32                 `protobuf:"varint,3,opt,name=total_quantity,json=totalQuantity,proto3" json:"total_quantity,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Desc          string                 `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Pick          uint32                 `protobuf:"varint,8,opt,name=pick,proto3" json:"pick,omitempty"`
	MinPerOrder   uint32                 `protobuf:"varint,9,opt,name=min_per_order,json=minPerOrder,proto3" json:"min_per_order,omitempty"`
	MaxPerOrder   uint32                 `protobuf:"varint,10,opt,name=max_per_order,json=maxPerOrder,proto3" json:"max_per_order,omitempty"`
	Quantity      uint32                 `protobuf:"varint,11,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Enable        bool                   `protobuf:"varint,12,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionTicketsResponse_Ticket) Reset() {
	*x = GetSessionTicketsResponse_Ticket{}
	mi := &file_tickets_tickets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionTicketsResponse_Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionTicketsResponse_Ticket) ProtoMessage() {}

func (x *GetSessionTicketsResponse_Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_tickets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionTicketsResponse_Ticket.ProtoReflect.Descriptor instead.
func (*GetSessionTicketsResponse_Ticket) Descriptor() ([]byte, []int) {
	return file_tickets_tickets_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetSessionTicketsResponse_Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSessionTicketsResponse_Ticket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSessionTicketsResponse_Ticket) GetTotalQuantity() uint32 {
	if x != nil {
		return x.TotalQuantity
	}
	return 0
}

func (x *GetSessionTicketsResponse_Ticket) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetSessionTicketsResponse_Ticket) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *GetSessionTicketsResponse_Ticket) GetPick() uint32 {
	if x != nil {
		return x.Pick
	}
	return 0
}

func (x *GetSessionTicketsResponse_Ticket) GetMinPerOrder() uint32 {
	if x != nil {
		return x.MinPerOrder
	}
	return 0
}

func (x *GetSessionTicketsResponse_Ticket) GetMaxPerOrder() uint32 {
	if x != nil {
		return x.MaxPerOrder
	}
	return 0
}

func (x *GetSessionTicketsResponse_Ticket) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GetSessionTicketsResponse_Ticket) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

var File_tickets_tickets_proto protoreflect.FileDescriptor

const file_tickets_tickets_proto_rawDesc = "" +
	"\n" +
	"\x15tickets/tickets.proto\x12\vapi.tickets\x1a\fcommon.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xb7\b\n" +
	"\x14AddTicketTypeRequest\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12#\n" +
	"\bquantity\x18\x03 \x01(\rB\a\xbaH\x04*\x02 \x00R\bquantity\x12.\n" +
	"\x05price\x18\x04 \x01(\tB\x18\xbaH\x15r\x132\x11^\\d+(\\.\\d{1,2})?$R\x05price\x12\x1c\n" +
	"\x04desc\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\x04desc\x12O\n" +
	"\bsessions\x18\x06 \x03(\v2).api.tickets.AddTicketTypeRequest.SessionB\b\xbaH\x05\x92\x01\x02\b\x01R\bsessions\x12\x1e\n" +
	"\n" +
	"visibility\x18\n" +
	" \x01(\bR\n" +
	"visibility\x12I\n" +
	"\x10start_showing_on\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0estartShowingOn\x88\x01\x01\x12G\n" +
	"\x0fstop_showing_on\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x01R\rstopShowingOn\x88\x01\x01\x12\x1b\n" +
	"\x04pick\x18\v \x01(\rB\a\xbaH\x04*\x02(\x00R\x04pick\x12<\n" +
	"\x16min_quantity_per_order\x18\f \x01(\rB\a\xbaH\x04*\x02 \x00R\x13minQuantityPerOrder\x12<\n" +
	"\x16max_quantity_per_order\x18\r \x01(\rB\a\xbaH\x04*\x02 \x00R\x13maxQuantityPerOrder\x12A\n" +
	"\fdue_duration\x18\x0e \x01(\v2\x19.google.protobuf.DurationH\x02R\vdueDuration\x88\x01\x01\x12\x1e\n" +
	"\x05event\x18\x0f \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05event\x12\x16\n" +
	"\x06enable\x18\x10 \x01(\bR\x06enable\x12*\n" +
	"\x11sale_time_setting\x18\a \x01(\tR\x0fsaleTimeSetting\x1a\xa9\x01\n" +
	"\aSession\x12\"\n" +
	"\asession\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\asession\x12>\n" +
	"\rsale_start_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vsaleStartAt\x12:\n" +
	"\vsale_end_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tsaleEndAt:U\xbaHR\x1aP\n" +
	"\x13max_gt_min_quantity\x1a9this.max_quantity_per_order > this.min_quantity_per_orderB\x13\n" +
	"\x11_start_showing_onB\x12\n" +
	"\x10_stop_showing_onB\x0f\n" +
	"\r_due_durationJ\x04\b\x01\x10\x02R\asession\"<\n" +
	"\x1aGetEventTicketTypesRequest\x12\x1e\n" +
	"\x05event\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05event\"\xf9\a\n" +
	"\x1bGetEventTicketTypesResponse\x12C\n" +
	"\x04data\x18\x01 \x03(\v2/.api.tickets.GetEventTicketTypesResponse.TicketR\x04data\x1a\xec\x06\n" +
	"\x06Ticket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\x121\n" +
	"\x05price\x18\x04 \x01(\tB\x1b\xbaH\x18r\x162\x14^\\\\d+(\\\\.\\\\d{1,2})?$R\x05price\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\x12\x1e\n" +
	"\n" +
	"visibility\x18\b \x01(\bR\n" +
	"visibility\x12D\n" +
	"\x10start_showing_on\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0estartShowingOn\x12B\n" +
	"\x0fstop_showing_on\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rstopShowingOn\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12(\n" +
	"\n" +
	"created_by\x18\r \x01(\v2\t.api.UserR\tcreatedBy\x12(\n" +
	"\n" +
	"updated_by\x18\x0e \x01(\v2\t.api.UserR\tupdatedBy\x12\x12\n" +
	"\x04pick\x18\x0f \x01(\rR\x04pick\x123\n" +
	"\x16min_quantity_per_order\x18\x10 \x01(\rR\x13minQuantityPerOrder\x123\n" +
	"\x16max_quantity_per_order\x18\x11 \x01(\rR\x13maxQuantityPerOrder\x12`\n" +
	"\rsessions_info\x18\x12 \x03(\v2;.api.tickets.GetEventTicketTypesResponse.Ticket.SessionInfoR\fsessionsInfo\x12\x16\n" +
	"\x06enable\x18\x13 \x01(\bR\x06enable\x12*\n" +
	"\x11sale_time_setting\x18\x14 \x01(\tR\x0fsaleTimeSetting\x1aC\n" +
	"\vSessionInfo\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantityJ\x04\b\x06\x10\aJ\x04\b\a\x10\bR\rsale_start_atR\vsale_end_at\";\n" +
	"\x17DeleteTicketTypeRequest\x12 \n" +
	"\x06ticket\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x06ticket\"\x8f\t\n" +
	"\x17UpdateTicketTypeRequest\x12 \n" +
	"\x06ticket\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x06ticket\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12#\n" +
	"\bquantity\x18\x03 \x01(\rB\a\xbaH\x04*\x02 \x00R\bquantity\x12.\n" +
	"\x05price\x18\x04 \x01(\tB\x18\xbaH\x15r\x132\x11^\\d+(\\.\\d{1,2})?$R\x05price\x12\x1c\n" +
	"\x04desc\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\x04desc\x12>\n" +
	"\rsale_start_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vsaleStartAt\x12:\n" +
	"\vsale_end_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tsaleEndAt\x12\x1e\n" +
	"\n" +
	"visibility\x18\b \x01(\bR\n" +
	"visibility\x12I\n" +
	"\x10start_showing_on\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0estartShowingOn\x88\x01\x01\x12G\n" +
	"\x0fstop_showing_on\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x01R\rstopShowingOn\x88\x01\x01\x12<\n" +
	"\x16min_quantity_per_order\x18\v \x01(\rB\a\xbaH\x04*\x02 \x00R\x13minQuantityPerOrder\x12<\n" +
	"\x16max_quantity_per_order\x18\f \x01(\rB\a\xbaH\x04*\x02 \x00R\x13maxQuantityPerOrder\x12A\n" +
	"\fdue_duration\x18\r \x01(\v2\x19.google.protobuf.DurationH\x02R\vdueDuration\x88\x01\x01\x12*\n" +
	"\x11sale_time_setting\x18\x0e \x01(\tR\x0fsaleTimeSetting\x12R\n" +
	"\bsessions\x18\x0f \x03(\v2,.api.tickets.UpdateTicketTypeRequest.SessionB\b\xbaH\x05\x92\x01\x02\b\x01R\bsessions\x12\x16\n" +
	"\x06enable\x18\x10 \x01(\bR\x06enable\x1a\xa9\x01\n" +
	"\aSession\x12\"\n" +
	"\asession\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\asession\x12>\n" +
	"\rsale_start_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vsaleStartAt\x12:\n" +
	"\vsale_end_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tsaleEndAt:U\xbaHR\x1aP\n" +
	"\x13max_gt_min_quantity\x1a9this.max_quantity_per_order > this.min_quantity_per_orderB\x13\n" +
	"\x11_start_showing_onB\x12\n" +
	"\x10_stop_showing_onB\x0f\n" +
	"\r_due_duration\"h\n" +
	"\x1dUpdateTicketTypesOrderRequest\x12\x1e\n" +
	"\x05event\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05event\x12'\n" +
	"\x05order\x18\x02 \x03(\tB\x11\xbaH\x0e\x92\x01\v\b\x02\x18\x01\"\x05r\x03\x98\x01\x18R\x05order\">\n" +
	"\x18GetSessionTicketsRequest\x12\"\n" +
	"\asession\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\asession\"\x96\x03\n" +
	"\x19GetSessionTicketsResponse\x12A\n" +
	"\x04data\x18\x01 \x03(\v2-.api.tickets.GetSessionTicketsResponse.TicketR\x04data\x1a\xb5\x02\n" +
	"\x06Ticket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0etotal_quantity\x18\x03 \x01(\rR\rtotalQuantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\x12\x12\n" +
	"\x04pick\x18\b \x01(\rR\x04pick\x12\"\n" +
	"\rmin_per_order\x18\t \x01(\rR\vminPerOrder\x12\"\n" +
	"\rmax_per_order\x18\n" +
	" \x01(\rR\vmaxPerOrder\x12\x1a\n" +
	"\bquantity\x18\v \x01(\rR\bquantity\x12\x16\n" +
	"\x06enable\x18\f \x01(\bR\x06enableJ\x04\b\x06\x10\aJ\x04\b\a\x10\bR\rsale_start_atR\vsale_end_at\"8\n" +
	"\x14CheckInTicketRequest\x12 \n" +
	"\aqr_code\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06qrCode\"\xf6\x01\n" +
	"\x15CheckInTicketResponse\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x123\n" +
	"\aused_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06usedAt\x12%\n" +
	"\bcustomer\x18\x04 \x01(\v2\t.api.UserR\bcustomer\x12&\n" +
	"\x0forder_item_name\x18\x05 \x01(\tR\rorderItemName\x12$\n" +
	"\x0echecked_in_now\x18\x06 \x01(\bR\fcheckedInNow2\xfa\x01\n" +
	"\x0eTicketsService\x12q\n" +
	"\x0fGetEventTickets\x12'.api.tickets.GetEventTicketTypesRequest\x1a\r.api.Response\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/v1/events/{event}/tickets\x12u\n" +
	"\x11GetSessionTickets\x12%.api.tickets.GetSessionTicketsRequest\x1a\r.api.Response\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/sessions/{session}/tickets2\xf2\x05\n" +
	"\x13TicketsAdminService\x12n\n" +
	"\rCheckInTicket\x12!.api.tickets.CheckInTicketRequest\x1a\r.api.Response\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/console/tickets:check-in\x12t\n" +
	"\rAddTicketType\x12!.api.tickets.AddTicketTypeRequest\x1a\r.api.Response\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/console/events/{event}/tickets\x12}\n" +
	"\x13GetEventTicketTypes\x12'.api.tickets.GetEventTicketTypesRequest\x1a\r.api.Response\".\x82\xd3\xe4\x93\x02(\x12&/api/v1/console/events/{event}/tickets\x12q\n" +
	"\x10DeleteTicketType\x12$.api.tickets.DeleteTicketTypeRequest\x1a\r.api.Response\"(\x82\xd3\xe4\x93\x02\"* /api/v1/console/tickets/{ticket}\x12t\n" +
	"\x10UpdateTicketType\x12$.api.tickets.UpdateTicketTypeRequest\x1a\r.api.Response\"+\x82\xd3\xe4\x93\x02%:\x01*\x1a /api/v1/console/tickets/{ticket}\x12\x8c\x01\n" +
	"\x16UpdateTicketTypesOrder\x12*.api.tickets.UpdateTicketTypesOrderRequest\x1a\r.api.Response\"7\x82\xd3\xe4\x93\x021:\x01*2,/api/v1/console/events/{event}/tickets/orderB\x1dZ\x1bpartivo_tickets/api/ticketsb\x06proto3"

var (
	file_tickets_tickets_proto_rawDescOnce sync.Once
	file_tickets_tickets_proto_rawDescData []byte
)

func file_tickets_tickets_proto_rawDescGZIP() []byte {
	file_tickets_tickets_proto_rawDescOnce.Do(func() {
		file_tickets_tickets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tickets_tickets_proto_rawDesc), len(file_tickets_tickets_proto_rawDesc)))
	})
	return file_tickets_tickets_proto_rawDescData
}

var file_tickets_tickets_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_tickets_tickets_proto_goTypes = []any{
	(*AddTicketTypeRequest)(nil),                           // 0: api.tickets.AddTicketTypeRequest
	(*GetEventTicketTypesRequest)(nil),                     // 1: api.tickets.GetEventTicketTypesRequest
	(*GetEventTicketTypesResponse)(nil),                    // 2: api.tickets.GetEventTicketTypesResponse
	(*DeleteTicketTypeRequest)(nil),                        // 3: api.tickets.DeleteTicketTypeRequest
	(*UpdateTicketTypeRequest)(nil),                        // 4: api.tickets.UpdateTicketTypeRequest
	(*UpdateTicketTypesOrderRequest)(nil),                  // 5: api.tickets.UpdateTicketTypesOrderRequest
	(*GetSessionTicketsRequest)(nil),                       // 6: api.tickets.GetSessionTicketsRequest
	(*GetSessionTicketsResponse)(nil),                      // 7: api.tickets.GetSessionTicketsResponse
	(*CheckInTicketRequest)(nil),                           // 8: api.tickets.CheckInTicketRequest
	(*CheckInTicketResponse)(nil),                          // 9: api.tickets.CheckInTicketResponse
	(*AddTicketTypeRequest_Session)(nil),                   // 10: api.tickets.AddTicketTypeRequest.Session
	(*GetEventTicketTypesResponse_Ticket)(nil),             // 11: api.tickets.GetEventTicketTypesResponse.Ticket
	(*GetEventTicketTypesResponse_Ticket_SessionInfo)(nil), // 12: api.tickets.GetEventTicketTypesResponse.Ticket.SessionInfo
	(*UpdateTicketTypeRequest_Session)(nil),                // 13: api.tickets.UpdateTicketTypeRequest.Session
	(*GetSessionTicketsResponse_Ticket)(nil),               // 14: api.tickets.GetSessionTicketsResponse.Ticket
	(*timestamppb.Timestamp)(nil),                          // 15: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                            // 16: google.protobuf.Duration
	(*api.User)(nil),                                       // 17: api.User
	(*api.Response)(nil),                                   // 18: api.Response
}
var file_tickets_tickets_proto_depIdxs = []int32{
	10, // 0: api.tickets.AddTicketTypeRequest.sessions:type_name -> api.tickets.AddTicketTypeRequest.Session
	15, // 1: api.tickets.AddTicketTypeRequest.start_showing_on:type_name -> google.protobuf.Timestamp
	15, // 2: api.tickets.AddTicketTypeRequest.stop_showing_on:type_name -> google.protobuf.Timestamp
	16, // 3: api.tickets.AddTicketTypeRequest.due_duration:type_name -> google.protobuf.Duration
	11, // 4: api.tickets.GetEventTicketTypesResponse.data:type_name -> api.tickets.GetEventTicketTypesResponse.Ticket
	15, // 5: api.tickets.UpdateTicketTypeRequest.sale_start_at:type_name -> google.protobuf.Timestamp
	15, // 6: api.tickets.UpdateTicketTypeRequest.sale_end_at:type_name -> google.protobuf.Timestamp
	15, // 7: api.tickets.UpdateTicketTypeRequest.start_showing_on:type_name -> google.protobuf.Timestamp
	15, // 8: api.tickets.UpdateTicketTypeRequest.stop_showing_on:type_name -> google.protobuf.Timestamp
	16, // 9: api.tickets.UpdateTicketTypeRequest.due_duration:type_name -> google.protobuf.Duration
	13, // 10: api.tickets.UpdateTicketTypeRequest.sessions:type_name -> api.tickets.UpdateTicketTypeRequest.Session
	14, // 11: api.tickets.GetSessionTicketsResponse.data:type_name -> api.tickets.GetSessionTicketsResponse.Ticket
	15, // 12: api.tickets.CheckInTicketResponse.used_at:type_name -> google.protobuf.Timestamp
	17, // 13: api.tickets.CheckInTicketResponse.customer:type_name -> api.User
	15, // 14: api.tickets.AddTicketTypeRequest.Session.sale_start_at:type_name -> google.protobuf.Timestamp
	15, // 15: api.tickets.AddTicketTypeRequest.Session.sale_end_at:type_name -> google.protobuf.Timestamp
	15, // 16: api.tickets.GetEventTicketTypesResponse.Ticket.start_showing_on:type_name -> google.protobuf.Timestamp
	15, // 17: api.tickets.GetEventTicketTypesResponse.Ticket.stop_showing_on:type_name -> google.protobuf.Timestamp
	15, // 18: api.tickets.GetEventTicketTypesResponse.Ticket.created_at:type_name -> google.protobuf.Timestamp
	15, // 19: api.tickets.GetEventTicketTypesResponse.Ticket.updated_at:type_name -> google.protobuf.Timestamp
	17, // 20: api.tickets.GetEventTicketTypesResponse.Ticket.created_by:type_name -> api.User
	17, // 21: api.tickets.GetEventTicketTypesResponse.Ticket.updated_by:type_name -> api.User
	12, // 22: api.tickets.GetEventTicketTypesResponse.Ticket.sessions_info:type_name -> api.tickets.GetEventTicketTypesResponse.Ticket.SessionInfo
	15, // 23: api.tickets.UpdateTicketTypeRequest.Session.sale_start_at:type_name -> google.protobuf.Timestamp
	15, // 24: api.tickets.UpdateTicketTypeRequest.Session.sale_end_at:type_name -> google.protobuf.Timestamp
	1,  // 25: api.tickets.TicketsService.GetEventTickets:input_type -> api.tickets.GetEventTicketTypesRequest
	6,  // 26: api.tickets.TicketsService.GetSessionTickets:input_type -> api.tickets.GetSessionTicketsRequest
	8,  // 27: api.tickets.TicketsAdminService.CheckInTicket:input_type -> api.tickets.CheckInTicketRequest
	0,  // 28: api.tickets.TicketsAdminService.AddTicketType:input_type -> api.tickets.AddTicketTypeRequest
	1,  // 29: api.tickets.TicketsAdminService.GetEventTicketTypes:input_type -> api.tickets.GetEventTicketTypesRequest
	3,  // 30: api.tickets.TicketsAdminService.DeleteTicketType:input_type -> api.tickets.DeleteTicketTypeRequest
	4,  // 31: api.tickets.TicketsAdminService.UpdateTicketType:input_type -> api.tickets.UpdateTicketTypeRequest
	5,  // 32: api.tickets.TicketsAdminService.UpdateTicketTypesOrder:input_type -> api.tickets.UpdateTicketTypesOrderRequest
	18, // 33: api.tickets.TicketsService.GetEventTickets:output_type -> api.Response
	18, // 34: api.tickets.TicketsService.GetSessionTickets:output_type -> api.Response
	18, // 35: api.tickets.TicketsAdminService.CheckInTicket:output_type -> api.Response
	18, // 36: api.tickets.TicketsAdminService.AddTicketType:output_type -> api.Response
	18, // 37: api.tickets.TicketsAdminService.GetEventTicketTypes:output_type -> api.Response
	18, // 38: api.tickets.TicketsAdminService.DeleteTicketType:output_type -> api.Response
	18, // 39: api.tickets.TicketsAdminService.UpdateTicketType:output_type -> api.Response
	18, // 40: api.tickets.TicketsAdminService.UpdateTicketTypesOrder:output_type -> api.Response
	33, // [33:41] is the sub-list for method output_type
	25, // [25:33] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_tickets_tickets_proto_init() }
func file_tickets_tickets_proto_init() {
	if File_tickets_tickets_proto != nil {
		return
	}
	file_tickets_tickets_proto_msgTypes[0].OneofWrappers = []any{}
	file_tickets_tickets_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tickets_tickets_proto_rawDesc), len(file_tickets_tickets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_tickets_tickets_proto_goTypes,
		DependencyIndexes: file_tickets_tickets_proto_depIdxs,
		MessageInfos:      file_tickets_tickets_proto_msgTypes,
	}.Build()
	File_tickets_tickets_proto = out.File
	file_tickets_tickets_proto_goTypes = nil
	file_tickets_tickets_proto_depIdxs = nil
}
