// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: bills/bills.proto

package bills

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	api "partivo_tickets/api"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillService_GetTransactionHistory_FullMethodName = "/api.bills.BillService/GetTransactionHistory"
)

// BillServiceClient is the client API for BillService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillServiceClient interface {
	GetTransactionHistory(ctx context.Context, in *GetTransactionHistoryRequest, opts ...grpc.CallOption) (*api.Response, error)
}

type billServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillServiceClient(cc grpc.ClientConnInterface) BillServiceClient {
	return &billServiceClient{cc}
}

func (c *billServiceClient) GetTransactionHistory(ctx context.Context, in *GetTransactionHistoryRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, BillService_GetTransactionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillServiceServer is the server API for BillService service.
// All implementations must embed UnimplementedBillServiceServer
// for forward compatibility.
type BillServiceServer interface {
	GetTransactionHistory(context.Context, *GetTransactionHistoryRequest) (*api.Response, error)
	mustEmbedUnimplementedBillServiceServer()
}

// UnimplementedBillServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillServiceServer struct{}

func (UnimplementedBillServiceServer) GetTransactionHistory(context.Context, *GetTransactionHistoryRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionHistory not implemented")
}
func (UnimplementedBillServiceServer) mustEmbedUnimplementedBillServiceServer() {}
func (UnimplementedBillServiceServer) testEmbeddedByValue()                     {}

// UnsafeBillServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillServiceServer will
// result in compilation errors.
type UnsafeBillServiceServer interface {
	mustEmbedUnimplementedBillServiceServer()
}

func RegisterBillServiceServer(s grpc.ServiceRegistrar, srv BillServiceServer) {
	// If the following call pancis, it indicates UnimplementedBillServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillService_ServiceDesc, srv)
}

func _BillService_GetTransactionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillServiceServer).GetTransactionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillService_GetTransactionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillServiceServer).GetTransactionHistory(ctx, req.(*GetTransactionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillService_ServiceDesc is the grpc.ServiceDesc for BillService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.bills.BillService",
	HandlerType: (*BillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransactionHistory",
			Handler:    _BillService_GetTransactionHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bills/bills.proto",
}

const (
	BillAdminService_CreateBill_FullMethodName       = "/api.bills.BillAdminService/CreateBill"
	BillAdminService_CancelBill_FullMethodName       = "/api.bills.BillAdminService/CancelBill"
	BillAdminService_CreateRefundBill_FullMethodName = "/api.bills.BillAdminService/CreateRefundBill"
	BillAdminService_GetBillsByOrder_FullMethodName  = "/api.bills.BillAdminService/GetBillsByOrder"
)

// BillAdminServiceClient is the client API for BillAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillAdminServiceClient interface {
	CreateBill(ctx context.Context, in *CreateBillRequest, opts ...grpc.CallOption) (*api.Response, error)
	CancelBill(ctx context.Context, in *CancelBillRequest, opts ...grpc.CallOption) (*api.Response, error)
	CreateRefundBill(ctx context.Context, in *CreateRefundBillRequest, opts ...grpc.CallOption) (*api.Response, error)
	GetBillsByOrder(ctx context.Context, in *GetBillsByOrderRequest, opts ...grpc.CallOption) (*api.Response, error)
}

type billAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillAdminServiceClient(cc grpc.ClientConnInterface) BillAdminServiceClient {
	return &billAdminServiceClient{cc}
}

func (c *billAdminServiceClient) CreateBill(ctx context.Context, in *CreateBillRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, BillAdminService_CreateBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billAdminServiceClient) CancelBill(ctx context.Context, in *CancelBillRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, BillAdminService_CancelBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billAdminServiceClient) CreateRefundBill(ctx context.Context, in *CreateRefundBillRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, BillAdminService_CreateRefundBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billAdminServiceClient) GetBillsByOrder(ctx context.Context, in *GetBillsByOrderRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, BillAdminService_GetBillsByOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillAdminServiceServer is the server API for BillAdminService service.
// All implementations must embed UnimplementedBillAdminServiceServer
// for forward compatibility.
type BillAdminServiceServer interface {
	CreateBill(context.Context, *CreateBillRequest) (*api.Response, error)
	CancelBill(context.Context, *CancelBillRequest) (*api.Response, error)
	CreateRefundBill(context.Context, *CreateRefundBillRequest) (*api.Response, error)
	GetBillsByOrder(context.Context, *GetBillsByOrderRequest) (*api.Response, error)
	mustEmbedUnimplementedBillAdminServiceServer()
}

// UnimplementedBillAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillAdminServiceServer struct{}

func (UnimplementedBillAdminServiceServer) CreateBill(context.Context, *CreateBillRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBill not implemented")
}
func (UnimplementedBillAdminServiceServer) CancelBill(context.Context, *CancelBillRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelBill not implemented")
}
func (UnimplementedBillAdminServiceServer) CreateRefundBill(context.Context, *CreateRefundBillRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRefundBill not implemented")
}
func (UnimplementedBillAdminServiceServer) GetBillsByOrder(context.Context, *GetBillsByOrderRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBillsByOrder not implemented")
}
func (UnimplementedBillAdminServiceServer) mustEmbedUnimplementedBillAdminServiceServer() {}
func (UnimplementedBillAdminServiceServer) testEmbeddedByValue()                          {}

// UnsafeBillAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillAdminServiceServer will
// result in compilation errors.
type UnsafeBillAdminServiceServer interface {
	mustEmbedUnimplementedBillAdminServiceServer()
}

func RegisterBillAdminServiceServer(s grpc.ServiceRegistrar, srv BillAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedBillAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillAdminService_ServiceDesc, srv)
}

func _BillAdminService_CreateBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillAdminServiceServer).CreateBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillAdminService_CreateBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillAdminServiceServer).CreateBill(ctx, req.(*CreateBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillAdminService_CancelBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillAdminServiceServer).CancelBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillAdminService_CancelBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillAdminServiceServer).CancelBill(ctx, req.(*CancelBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillAdminService_CreateRefundBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRefundBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillAdminServiceServer).CreateRefundBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillAdminService_CreateRefundBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillAdminServiceServer).CreateRefundBill(ctx, req.(*CreateRefundBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillAdminService_GetBillsByOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillsByOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillAdminServiceServer).GetBillsByOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillAdminService_GetBillsByOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillAdminServiceServer).GetBillsByOrder(ctx, req.(*GetBillsByOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillAdminService_ServiceDesc is the grpc.ServiceDesc for BillAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.bills.BillAdminService",
	HandlerType: (*BillAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBill",
			Handler:    _BillAdminService_CreateBill_Handler,
		},
		{
			MethodName: "CancelBill",
			Handler:    _BillAdminService_CancelBill_Handler,
		},
		{
			MethodName: "CreateRefundBill",
			Handler:    _BillAdminService_CreateRefundBill_Handler,
		},
		{
			MethodName: "GetBillsByOrder",
			Handler:    _BillAdminService_GetBillsByOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bills/bills.proto",
}
