// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: bills/bills.proto

package bills

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	api "partivo_tickets/api"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethod) Reset() {
	*x = PaymentMethod{}
	mi := &file_bills_bills_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethod) ProtoMessage() {}

func (x *PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_bills_bills_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethod.ProtoReflect.Descriptor instead.
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return file_bills_bills_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateBillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         string                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod *PaymentMethod         `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBillRequest) Reset() {
	*x = CreateBillRequest{}
	mi := &file_bills_bills_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillRequest) ProtoMessage() {}

func (x *CreateBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bills_bills_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillRequest.ProtoReflect.Descriptor instead.
func (*CreateBillRequest) Descriptor() ([]byte, []int) {
	return file_bills_bills_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBillRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *CreateBillRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateBillRequest) GetPaymentMethod() *PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

type CancelBillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBillRequest) Reset() {
	*x = CancelBillRequest{}
	mi := &file_bills_bills_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBillRequest) ProtoMessage() {}

func (x *CancelBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bills_bills_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBillRequest.ProtoReflect.Descriptor instead.
func (*CancelBillRequest) Descriptor() ([]byte, []int) {
	return file_bills_bills_proto_rawDescGZIP(), []int{2}
}

func (x *CancelBillRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelBillRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CreateRefundBillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderItemId   string                 `protobuf:"bytes,1,opt,name=order_item_id,json=orderItemId,proto3" json:"order_item_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod *PaymentMethod         `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRefundBillRequest) Reset() {
	*x = CreateRefundBillRequest{}
	mi := &file_bills_bills_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundBillRequest) ProtoMessage() {}

func (x *CreateRefundBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bills_bills_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundBillRequest.ProtoReflect.Descriptor instead.
func (*CreateRefundBillRequest) Descriptor() ([]byte, []int) {
	return file_bills_bills_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRefundBillRequest) GetOrderItemId() string {
	if x != nil {
		return x.OrderItemId
	}
	return ""
}

func (x *CreateRefundBillRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateRefundBillRequest) GetPaymentMethod() *PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

func (x *CreateRefundBillRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetBillsByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillsByOrderRequest) Reset() {
	*x = GetBillsByOrderRequest{}
	mi := &file_bills_bills_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillsByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillsByOrderRequest) ProtoMessage() {}

func (x *GetBillsByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bills_bills_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillsByOrderRequest.ProtoReflect.Descriptor instead.
func (*GetBillsByOrderRequest) Descriptor() ([]byte, []int) {
	return file_bills_bills_proto_rawDescGZIP(), []int{4}
}

func (x *GetBillsByOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type Bill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Note          string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	PaymentMethod *PaymentMethod         `protobuf:"bytes,7,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaymentId     string                 `protobuf:"bytes,8,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bill) Reset() {
	*x = Bill{}
	mi := &file_bills_bills_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bill) ProtoMessage() {}

func (x *Bill) ProtoReflect() protoreflect.Message {
	mi := &file_bills_bills_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bill.ProtoReflect.Descriptor instead.
func (*Bill) Descriptor() ([]byte, []int) {
	return file_bills_bills_proto_rawDescGZIP(), []int{5}
}

func (x *Bill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bill) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Bill) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Bill) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Bill) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Bill) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Bill) GetPaymentMethod() *PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

func (x *Bill) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type GetBillsByOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bills         []*Bill                `protobuf:"bytes,1,rep,name=bills,proto3" json:"bills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillsByOrderResponse) Reset() {
	*x = GetBillsByOrderResponse{}
	mi := &file_bills_bills_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillsByOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillsByOrderResponse) ProtoMessage() {}

func (x *GetBillsByOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bills_bills_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillsByOrderResponse.ProtoReflect.Descriptor instead.
func (*GetBillsByOrderResponse) Descriptor() ([]byte, []int) {
	return file_bills_bills_proto_rawDescGZIP(), []int{6}
}

func (x *GetBillsByOrderResponse) GetBills() []*Bill {
	if x != nil {
		return x.Bills
	}
	return nil
}

type GetTransactionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryRequest) Reset() {
	*x = GetTransactionHistoryRequest{}
	mi := &file_bills_bills_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryRequest) ProtoMessage() {}

func (x *GetTransactionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bills_bills_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_bills_bills_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionHistoryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PaymentMethod *PaymentMethod         `protobuf:"bytes,6,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_bills_bills_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_bills_bills_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_bills_bills_proto_rawDescGZIP(), []int{8}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Transaction) GetPaymentMethod() *PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

type GetTransactionHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryResponse) Reset() {
	*x = GetTransactionHistoryResponse{}
	mi := &file_bills_bills_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryResponse) ProtoMessage() {}

func (x *GetTransactionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bills_bills_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_bills_bills_proto_rawDescGZIP(), []int{9}
}

func (x *GetTransactionHistoryResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_bills_bills_proto protoreflect.FileDescriptor

const file_bills_bills_proto_rawDesc = "" +
	"\n" +
	"\x11bills/bills.proto\x12\tapi.bills\x1a\fcommon.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\rPaymentMethod\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\"\x95\x01\n" +
	"\x11CreateBillRequest\x12\x1e\n" +
	"\x05order\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05order\x12\x1f\n" +
	"\x06amount\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06amount\x12?\n" +
	"\x0epayment_method\x18\x03 \x01(\v2\x18.api.bills.PaymentMethodR\rpaymentMethod\"E\n" +
	"\x11CancelBillRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xc1\x01\n" +
	"\x17CreateRefundBillRequest\x12,\n" +
	"\rorder_item_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\vorderItemId\x12\x1f\n" +
	"\x06amount\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06amount\x12?\n" +
	"\x0epayment_method\x18\x03 \x01(\v2\x18.api.bills.PaymentMethodR\rpaymentMethod\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"=\n" +
	"\x16GetBillsByOrderRequest\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\aorderId\"\x89\x02\n" +
	"\x04Bill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12?\n" +
	"\x0epayment_method\x18\a \x01(\v2\x18.api.bills.PaymentMethodR\rpaymentMethod\x12\x1d\n" +
	"\n" +
	"payment_id\x18\b \x01(\tR\tpaymentId\"@\n" +
	"\x17GetBillsByOrderResponse\x12%\n" +
	"\x05bills\x18\x01 \x03(\v2\x0f.api.bills.BillR\x05bills\"C\n" +
	"\x1cGetTransactionHistoryRequest\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\aorderId\"\xdc\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12?\n" +
	"\x0epayment_method\x18\x06 \x01(\v2\x18.api.bills.PaymentMethodR\rpaymentMethod\"[\n" +
	"\x1dGetTransactionHistoryResponse\x12:\n" +
	"\ftransactions\x18\x01 \x03(\v2\x16.api.bills.TransactionR\ftransactions2\x8e\x01\n" +
	"\vBillService\x12\x7f\n" +
	"\x15GetTransactionHistory\x12'.api.bills.GetTransactionHistoryRequest\x1a\r.api.Response\".\x82\xd3\xe4\x93\x02(\x12&/api/v1/orders/{order_id}/transactions2\xc8\x03\n" +
	"\x10BillAdminService\x12j\n" +
	"\n" +
	"CreateBill\x12\x1c.api.bills.CreateBillRequest\x1a\r.api.Response\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/v1/console/orders/{order}/bills\x12g\n" +
	"\n" +
	"CancelBill\x12\x1c.api.bills.CancelBillRequest\x1a\r.api.Response\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/v1/console/bills/{id}:cancel\x12i\n" +
	"\x10CreateRefundBill\x12\".api.bills.CreateRefundBillRequest\x1a\r.api.Response\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/console/refunds\x12t\n" +
	"\x0fGetBillsByOrder\x12!.api.bills.GetBillsByOrderRequest\x1a\r.api.Response\"/\x82\xd3\xe4\x93\x02)\x12'/api/v1/console/orders/{order_id}/billsB\x1bZ\x19partivo_tickets/api/billsb\x06proto3"

var (
	file_bills_bills_proto_rawDescOnce sync.Once
	file_bills_bills_proto_rawDescData []byte
)

func file_bills_bills_proto_rawDescGZIP() []byte {
	file_bills_bills_proto_rawDescOnce.Do(func() {
		file_bills_bills_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bills_bills_proto_rawDesc), len(file_bills_bills_proto_rawDesc)))
	})
	return file_bills_bills_proto_rawDescData
}

var file_bills_bills_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bills_bills_proto_goTypes = []any{
	(*PaymentMethod)(nil),                 // 0: api.bills.PaymentMethod
	(*CreateBillRequest)(nil),             // 1: api.bills.CreateBillRequest
	(*CancelBillRequest)(nil),             // 2: api.bills.CancelBillRequest
	(*CreateRefundBillRequest)(nil),       // 3: api.bills.CreateRefundBillRequest
	(*GetBillsByOrderRequest)(nil),        // 4: api.bills.GetBillsByOrderRequest
	(*Bill)(nil),                          // 5: api.bills.Bill
	(*GetBillsByOrderResponse)(nil),       // 6: api.bills.GetBillsByOrderResponse
	(*GetTransactionHistoryRequest)(nil),  // 7: api.bills.GetTransactionHistoryRequest
	(*Transaction)(nil),                   // 8: api.bills.Transaction
	(*GetTransactionHistoryResponse)(nil), // 9: api.bills.GetTransactionHistoryResponse
	(*timestamppb.Timestamp)(nil),         // 10: google.protobuf.Timestamp
	(*api.Response)(nil),                  // 11: api.Response
}
var file_bills_bills_proto_depIdxs = []int32{
	0,  // 0: api.bills.CreateBillRequest.payment_method:type_name -> api.bills.PaymentMethod
	0,  // 1: api.bills.CreateRefundBillRequest.payment_method:type_name -> api.bills.PaymentMethod
	10, // 2: api.bills.Bill.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: api.bills.Bill.payment_method:type_name -> api.bills.PaymentMethod
	5,  // 4: api.bills.GetBillsByOrderResponse.bills:type_name -> api.bills.Bill
	10, // 5: api.bills.Transaction.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 6: api.bills.Transaction.payment_method:type_name -> api.bills.PaymentMethod
	8,  // 7: api.bills.GetTransactionHistoryResponse.transactions:type_name -> api.bills.Transaction
	7,  // 8: api.bills.BillService.GetTransactionHistory:input_type -> api.bills.GetTransactionHistoryRequest
	1,  // 9: api.bills.BillAdminService.CreateBill:input_type -> api.bills.CreateBillRequest
	2,  // 10: api.bills.BillAdminService.CancelBill:input_type -> api.bills.CancelBillRequest
	3,  // 11: api.bills.BillAdminService.CreateRefundBill:input_type -> api.bills.CreateRefundBillRequest
	4,  // 12: api.bills.BillAdminService.GetBillsByOrder:input_type -> api.bills.GetBillsByOrderRequest
	11, // 13: api.bills.BillService.GetTransactionHistory:output_type -> api.Response
	11, // 14: api.bills.BillAdminService.CreateBill:output_type -> api.Response
	11, // 15: api.bills.BillAdminService.CancelBill:output_type -> api.Response
	11, // 16: api.bills.BillAdminService.CreateRefundBill:output_type -> api.Response
	11, // 17: api.bills.BillAdminService.GetBillsByOrder:output_type -> api.Response
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_bills_bills_proto_init() }
func file_bills_bills_proto_init() {
	if File_bills_bills_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bills_bills_proto_rawDesc), len(file_bills_bills_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_bills_bills_proto_goTypes,
		DependencyIndexes: file_bills_bills_proto_depIdxs,
		MessageInfos:      file_bills_bills_proto_msgTypes,
	}.Build()
	File_bills_bills_proto = out.File
	file_bills_bills_proto_goTypes = nil
	file_bills_bills_proto_depIdxs = nil
}
