// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: orders/orders.proto

package orders

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	api "partivo_tickets/api"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrdersAdminService_IsEventHasOpenOrders_FullMethodName  = "/api.orders.OrdersAdminService/IsEventHasOpenOrders"
	OrdersAdminService_GetOrdersByEvent_FullMethodName      = "/api.orders.OrdersAdminService/GetOrdersByEvent"
	OrdersAdminService_GetOrdersBySession_FullMethodName    = "/api.orders.OrdersAdminService/GetOrdersBySession"
	OrdersAdminService_ChangeOrderItemStatus_FullMethodName = "/api.orders.OrdersAdminService/ChangeOrderItemStatus"
	OrdersAdminService_GetOrderByID_FullMethodName          = "/api.orders.OrdersAdminService/GetOrderByID"
	OrdersAdminService_CancelOrder_FullMethodName           = "/api.orders.OrdersAdminService/CancelOrder"
	OrdersAdminService_RejectOrderItemRefund_FullMethodName = "/api.orders.OrdersAdminService/RejectOrderItemRefund"
)

// OrdersAdminServiceClient is the client API for OrdersAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrdersAdminServiceClient interface {
	IsEventHasOpenOrders(ctx context.Context, in *IsEventHasOrdersRequest, opts ...grpc.CallOption) (*api.Response, error)
	GetOrdersByEvent(ctx context.Context, in *GetOrdersByEventRequest, opts ...grpc.CallOption) (*api.Response, error)
	GetOrdersBySession(ctx context.Context, in *GetOrdersBySessionRequest, opts ...grpc.CallOption) (*api.Response, error)
	ChangeOrderItemStatus(ctx context.Context, in *ChangeOrderItemStatusRequest, opts ...grpc.CallOption) (*api.Response, error)
	GetOrderByID(ctx context.Context, in *GetOrderByIDRequest, opts ...grpc.CallOption) (*api.Response, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*api.Response, error)
	RejectOrderItemRefund(ctx context.Context, in *RejectOrderItemRefundRequest, opts ...grpc.CallOption) (*api.Response, error)
}

type ordersAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrdersAdminServiceClient(cc grpc.ClientConnInterface) OrdersAdminServiceClient {
	return &ordersAdminServiceClient{cc}
}

func (c *ordersAdminServiceClient) IsEventHasOpenOrders(ctx context.Context, in *IsEventHasOrdersRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, OrdersAdminService_IsEventHasOpenOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersAdminServiceClient) GetOrdersByEvent(ctx context.Context, in *GetOrdersByEventRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, OrdersAdminService_GetOrdersByEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersAdminServiceClient) GetOrdersBySession(ctx context.Context, in *GetOrdersBySessionRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, OrdersAdminService_GetOrdersBySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersAdminServiceClient) ChangeOrderItemStatus(ctx context.Context, in *ChangeOrderItemStatusRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, OrdersAdminService_ChangeOrderItemStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersAdminServiceClient) GetOrderByID(ctx context.Context, in *GetOrderByIDRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, OrdersAdminService_GetOrderByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersAdminServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, OrdersAdminService_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersAdminServiceClient) RejectOrderItemRefund(ctx context.Context, in *RejectOrderItemRefundRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, OrdersAdminService_RejectOrderItemRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrdersAdminServiceServer is the server API for OrdersAdminService service.
// All implementations must embed UnimplementedOrdersAdminServiceServer
// for forward compatibility.
type OrdersAdminServiceServer interface {
	IsEventHasOpenOrders(context.Context, *IsEventHasOrdersRequest) (*api.Response, error)
	GetOrdersByEvent(context.Context, *GetOrdersByEventRequest) (*api.Response, error)
	GetOrdersBySession(context.Context, *GetOrdersBySessionRequest) (*api.Response, error)
	ChangeOrderItemStatus(context.Context, *ChangeOrderItemStatusRequest) (*api.Response, error)
	GetOrderByID(context.Context, *GetOrderByIDRequest) (*api.Response, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*api.Response, error)
	RejectOrderItemRefund(context.Context, *RejectOrderItemRefundRequest) (*api.Response, error)
	mustEmbedUnimplementedOrdersAdminServiceServer()
}

// UnimplementedOrdersAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrdersAdminServiceServer struct{}

func (UnimplementedOrdersAdminServiceServer) IsEventHasOpenOrders(context.Context, *IsEventHasOrdersRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsEventHasOpenOrders not implemented")
}
func (UnimplementedOrdersAdminServiceServer) GetOrdersByEvent(context.Context, *GetOrdersByEventRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersByEvent not implemented")
}
func (UnimplementedOrdersAdminServiceServer) GetOrdersBySession(context.Context, *GetOrdersBySessionRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersBySession not implemented")
}
func (UnimplementedOrdersAdminServiceServer) ChangeOrderItemStatus(context.Context, *ChangeOrderItemStatusRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeOrderItemStatus not implemented")
}
func (UnimplementedOrdersAdminServiceServer) GetOrderByID(context.Context, *GetOrderByIDRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderByID not implemented")
}
func (UnimplementedOrdersAdminServiceServer) CancelOrder(context.Context, *CancelOrderRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedOrdersAdminServiceServer) RejectOrderItemRefund(context.Context, *RejectOrderItemRefundRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectOrderItemRefund not implemented")
}
func (UnimplementedOrdersAdminServiceServer) mustEmbedUnimplementedOrdersAdminServiceServer() {}
func (UnimplementedOrdersAdminServiceServer) testEmbeddedByValue()                            {}

// UnsafeOrdersAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrdersAdminServiceServer will
// result in compilation errors.
type UnsafeOrdersAdminServiceServer interface {
	mustEmbedUnimplementedOrdersAdminServiceServer()
}

func RegisterOrdersAdminServiceServer(s grpc.ServiceRegistrar, srv OrdersAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrdersAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrdersAdminService_ServiceDesc, srv)
}

func _OrdersAdminService_IsEventHasOpenOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsEventHasOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersAdminServiceServer).IsEventHasOpenOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdersAdminService_IsEventHasOpenOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersAdminServiceServer).IsEventHasOpenOrders(ctx, req.(*IsEventHasOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdersAdminService_GetOrdersByEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersByEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersAdminServiceServer).GetOrdersByEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdersAdminService_GetOrdersByEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersAdminServiceServer).GetOrdersByEvent(ctx, req.(*GetOrdersByEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdersAdminService_GetOrdersBySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersBySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersAdminServiceServer).GetOrdersBySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdersAdminService_GetOrdersBySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersAdminServiceServer).GetOrdersBySession(ctx, req.(*GetOrdersBySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdersAdminService_ChangeOrderItemStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeOrderItemStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersAdminServiceServer).ChangeOrderItemStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdersAdminService_ChangeOrderItemStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersAdminServiceServer).ChangeOrderItemStatus(ctx, req.(*ChangeOrderItemStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdersAdminService_GetOrderByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersAdminServiceServer).GetOrderByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdersAdminService_GetOrderByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersAdminServiceServer).GetOrderByID(ctx, req.(*GetOrderByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdersAdminService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersAdminServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdersAdminService_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersAdminServiceServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdersAdminService_RejectOrderItemRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectOrderItemRefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersAdminServiceServer).RejectOrderItemRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdersAdminService_RejectOrderItemRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersAdminServiceServer).RejectOrderItemRefund(ctx, req.(*RejectOrderItemRefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrdersAdminService_ServiceDesc is the grpc.ServiceDesc for OrdersAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrdersAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.orders.OrdersAdminService",
	HandlerType: (*OrdersAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsEventHasOpenOrders",
			Handler:    _OrdersAdminService_IsEventHasOpenOrders_Handler,
		},
		{
			MethodName: "GetOrdersByEvent",
			Handler:    _OrdersAdminService_GetOrdersByEvent_Handler,
		},
		{
			MethodName: "GetOrdersBySession",
			Handler:    _OrdersAdminService_GetOrdersBySession_Handler,
		},
		{
			MethodName: "ChangeOrderItemStatus",
			Handler:    _OrdersAdminService_ChangeOrderItemStatus_Handler,
		},
		{
			MethodName: "GetOrderByID",
			Handler:    _OrdersAdminService_GetOrderByID_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _OrdersAdminService_CancelOrder_Handler,
		},
		{
			MethodName: "RejectOrderItemRefund",
			Handler:    _OrdersAdminService_RejectOrderItemRefund_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orders/orders.proto",
}

const (
	OrderService_GetUserOrders_FullMethodName          = "/api.orders.OrderService/GetUserOrders"
	OrderService_AddOrder_FullMethodName               = "/api.orders.OrderService/AddOrder"
	OrderService_CancelOrder_FullMethodName            = "/api.orders.OrderService/CancelOrder"
	OrderService_RequestOrderItemRefund_FullMethodName = "/api.orders.OrderService/RequestOrderItemRefund"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, opts ...grpc.CallOption) (*api.Response, error)
	AddOrder(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*api.Response, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*api.Response, error)
	RequestOrderItemRefund(ctx context.Context, in *RequestOrderItemRefundRequest, opts ...grpc.CallOption) (*api.Response, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, OrderService_GetUserOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) AddOrder(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, OrderService_AddOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, OrderService_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) RequestOrderItemRefund(ctx context.Context, in *RequestOrderItemRefundRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, OrderService_RequestOrderItemRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility.
type OrderServiceServer interface {
	GetUserOrders(context.Context, *GetUserOrdersRequest) (*api.Response, error)
	AddOrder(context.Context, *AddOrderRequest) (*api.Response, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*api.Response, error)
	RequestOrderItemRefund(context.Context, *RequestOrderItemRefundRequest) (*api.Response, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceServer struct{}

func (UnimplementedOrderServiceServer) GetUserOrders(context.Context, *GetUserOrdersRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOrders not implemented")
}
func (UnimplementedOrderServiceServer) AddOrder(context.Context, *AddOrderRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrder not implemented")
}
func (UnimplementedOrderServiceServer) CancelOrder(context.Context, *CancelOrderRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedOrderServiceServer) RequestOrderItemRefund(context.Context, *RequestOrderItemRefundRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestOrderItemRefund not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}
func (UnimplementedOrderServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_GetUserOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetUserOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetUserOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetUserOrders(ctx, req.(*GetUserOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_AddOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).AddOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_AddOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).AddOrder(ctx, req.(*AddOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_RequestOrderItemRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestOrderItemRefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).RequestOrderItemRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_RequestOrderItemRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).RequestOrderItemRefund(ctx, req.(*RequestOrderItemRefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.orders.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserOrders",
			Handler:    _OrderService_GetUserOrders_Handler,
		},
		{
			MethodName: "AddOrder",
			Handler:    _OrderService_AddOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _OrderService_CancelOrder_Handler,
		},
		{
			MethodName: "RequestOrderItemRefund",
			Handler:    _OrderService_RequestOrderItemRefund_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orders/orders.proto",
}
