// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: orders/orders.proto

package orders

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	api "partivo_tickets/api"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeOrderItemStatusRequest_OrderItemStatus int32

const (
	ChangeOrderItemStatusRequest_UNKNOWN          ChangeOrderItemStatusRequest_OrderItemStatus = 0
	ChangeOrderItemStatusRequest_CANCELED         ChangeOrderItemStatusRequest_OrderItemStatus = 1
	ChangeOrderItemStatusRequest_RETURN_REQUESTED ChangeOrderItemStatusRequest_OrderItemStatus = 3
	ChangeOrderItemStatusRequest_RETURN_APPROVED  ChangeOrderItemStatusRequest_OrderItemStatus = 4
)

// Enum value maps for ChangeOrderItemStatusRequest_OrderItemStatus.
var (
	ChangeOrderItemStatusRequest_OrderItemStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "CANCELED",
		3: "RETURN_REQUESTED",
		4: "RETURN_APPROVED",
	}
	ChangeOrderItemStatusRequest_OrderItemStatus_value = map[string]int32{
		"UNKNOWN":          0,
		"CANCELED":         1,
		"RETURN_REQUESTED": 3,
		"RETURN_APPROVED":  4,
	}
)

func (x ChangeOrderItemStatusRequest_OrderItemStatus) Enum() *ChangeOrderItemStatusRequest_OrderItemStatus {
	p := new(ChangeOrderItemStatusRequest_OrderItemStatus)
	*p = x
	return p
}

func (x ChangeOrderItemStatusRequest_OrderItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeOrderItemStatusRequest_OrderItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orders_orders_proto_enumTypes[0].Descriptor()
}

func (ChangeOrderItemStatusRequest_OrderItemStatus) Type() protoreflect.EnumType {
	return &file_orders_orders_proto_enumTypes[0]
}

func (x ChangeOrderItemStatusRequest_OrderItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeOrderItemStatusRequest_OrderItemStatus.Descriptor instead.
func (ChangeOrderItemStatusRequest_OrderItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{8, 0}
}

type AddOrderRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Items         []*AddOrderRequest_Item        `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Subtotal      string                         `protobuf:"bytes,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Total         string                         `protobuf:"bytes,5,opt,name=total,proto3" json:"total,omitempty"`
	Event         string                         `protobuf:"bytes,7,opt,name=event,proto3" json:"event,omitempty"`
	MerchantId    string                         `protobuf:"bytes,8,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PaymentMethod *AddOrderRequest_PaymentMethod `protobuf:"bytes,9,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderRequest) Reset() {
	*x = AddOrderRequest{}
	mi := &file_orders_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRequest) ProtoMessage() {}

func (x *AddOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRequest.ProtoReflect.Descriptor instead.
func (*AddOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{0}
}

func (x *AddOrderRequest) GetItems() []*AddOrderRequest_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AddOrderRequest) GetSubtotal() string {
	if x != nil {
		return x.Subtotal
	}
	return ""
}

func (x *AddOrderRequest) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *AddOrderRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *AddOrderRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *AddOrderRequest) GetPaymentMethod() *AddOrderRequest_PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

type AddOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BillId        string                 `protobuf:"bytes,2,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderResponse) Reset() {
	*x = AddOrderResponse{}
	mi := &file_orders_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderResponse) ProtoMessage() {}

func (x *AddOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderResponse.ProtoReflect.Descriptor instead.
func (*AddOrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{1}
}

func (x *AddOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AddOrderResponse) GetBillId() string {
	if x != nil {
		return x.BillId
	}
	return ""
}

type IsEventHasOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsEventHasOrdersRequest) Reset() {
	*x = IsEventHasOrdersRequest{}
	mi := &file_orders_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsEventHasOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsEventHasOrdersRequest) ProtoMessage() {}

func (x *IsEventHasOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsEventHasOrdersRequest.ProtoReflect.Descriptor instead.
func (*IsEventHasOrdersRequest) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{2}
}

func (x *IsEventHasOrdersRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type GetOrdersByEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Page          *uint32                `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByEventRequest) Reset() {
	*x = GetOrdersByEventRequest{}
	mi := &file_orders_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByEventRequest) ProtoMessage() {}

func (x *GetOrdersByEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByEventRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersByEventRequest) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrdersByEventRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *GetOrdersByEventRequest) GetPage() uint32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

type GetOrdersResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Data          []*GetOrdersResponse_GetOrdersOrder `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	PageInfo      *api.PageInfo                       `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_orders_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrdersResponse) GetData() []*GetOrdersResponse_GetOrdersOrder {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetOrdersResponse) GetPageInfo() *api.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type GetOrdersBySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Page          *uint32                `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersBySessionRequest) Reset() {
	*x = GetOrdersBySessionRequest{}
	mi := &file_orders_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersBySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersBySessionRequest) ProtoMessage() {}

func (x *GetOrdersBySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersBySessionRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersBySessionRequest) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrdersBySessionRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *GetOrdersBySessionRequest) GetPage() uint32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

type GetUserOrdersResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Data          []*GetUserOrdersResponse_GetOrdersOrder `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	After         string                                  `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersResponse) Reset() {
	*x = GetUserOrdersResponse{}
	mi := &file_orders_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersResponse) ProtoMessage() {}

func (x *GetUserOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetUserOrdersResponse) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserOrdersResponse) GetData() []*GetUserOrdersResponse_GetOrdersOrder {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetUserOrdersResponse) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

type GetUserOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	After         *string                `protobuf:"bytes,1,opt,name=after,proto3,oneof" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersRequest) Reset() {
	*x = GetUserOrdersRequest{}
	mi := &file_orders_orders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersRequest) ProtoMessage() {}

func (x *GetUserOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetUserOrdersRequest) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserOrdersRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

type ChangeOrderItemStatusRequest struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Order         string                                       `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Item          string                                       `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Status        ChangeOrderItemStatusRequest_OrderItemStatus `protobuf:"varint,3,opt,name=status,proto3,enum=api.orders.ChangeOrderItemStatusRequest_OrderItemStatus" json:"status,omitempty"`
	Reason        string                                       `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeOrderItemStatusRequest) Reset() {
	*x = ChangeOrderItemStatusRequest{}
	mi := &file_orders_orders_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeOrderItemStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeOrderItemStatusRequest) ProtoMessage() {}

func (x *ChangeOrderItemStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeOrderItemStatusRequest.ProtoReflect.Descriptor instead.
func (*ChangeOrderItemStatusRequest) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeOrderItemStatusRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *ChangeOrderItemStatusRequest) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *ChangeOrderItemStatusRequest) GetStatus() ChangeOrderItemStatusRequest_OrderItemStatus {
	if x != nil {
		return x.Status
	}
	return ChangeOrderItemStatusRequest_UNKNOWN
}

func (x *ChangeOrderItemStatusRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetOrderByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         string                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDRequest) Reset() {
	*x = GetOrderByIDRequest{}
	mi := &file_orders_orders_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDRequest) ProtoMessage() {}

func (x *GetOrderByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByIDRequest) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderByIDRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         string                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Reason        *string                `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_orders_orders_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{10}
}

func (x *CancelOrderRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *CancelOrderRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type RequestOrderItemRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         string                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Item          string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOrderItemRefundRequest) Reset() {
	*x = RequestOrderItemRefundRequest{}
	mi := &file_orders_orders_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOrderItemRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOrderItemRefundRequest) ProtoMessage() {}

func (x *RequestOrderItemRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOrderItemRefundRequest.ProtoReflect.Descriptor instead.
func (*RequestOrderItemRefundRequest) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{11}
}

func (x *RequestOrderItemRefundRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *RequestOrderItemRefundRequest) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *RequestOrderItemRefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RejectOrderItemRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         string                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Item          string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectOrderItemRefundRequest) Reset() {
	*x = RejectOrderItemRefundRequest{}
	mi := &file_orders_orders_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectOrderItemRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectOrderItemRefundRequest) ProtoMessage() {}

func (x *RejectOrderItemRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectOrderItemRefundRequest.ProtoReflect.Descriptor instead.
func (*RejectOrderItemRefundRequest) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{12}
}

func (x *RejectOrderItemRefundRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *RejectOrderItemRefundRequest) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *RejectOrderItemRefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Order         *GetOrderResponse_Order  `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Items         []*GetOrderResponse_Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Bills         []*GetOrderResponse_Bill `protobuf:"bytes,3,rep,name=bills,proto3" json:"bills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_orders_orders_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrderResponse) GetOrder() *GetOrderResponse_Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *GetOrderResponse) GetItems() []*GetOrderResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetOrderResponse) GetBills() []*GetOrderResponse_Bill {
	if x != nil {
		return x.Bills
	}
	return nil
}

type AddOrderRequest_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        string                 `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderRequest_Item) Reset() {
	*x = AddOrderRequest_Item{}
	mi := &file_orders_orders_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderRequest_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRequest_Item) ProtoMessage() {}

func (x *AddOrderRequest_Item) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRequest_Item.ProtoReflect.Descriptor instead.
func (*AddOrderRequest_Item) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AddOrderRequest_Item) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *AddOrderRequest_Item) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddOrderRequest_PaymentMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderRequest_PaymentMethod) Reset() {
	*x = AddOrderRequest_PaymentMethod{}
	mi := &file_orders_orders_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderRequest_PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRequest_PaymentMethod) ProtoMessage() {}

func (x *AddOrderRequest_PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRequest_PaymentMethod.ProtoReflect.Descriptor instead.
func (*AddOrderRequest_PaymentMethod) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AddOrderRequest_PaymentMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddOrderRequest_PaymentMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetOrdersResponse_GetOrdersOrder struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Id            string                                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Items         []*GetOrdersResponse_GetOrdersOrder_Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Subtotal      string                                   `protobuf:"bytes,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Total         string                                   `protobuf:"bytes,5,opt,name=total,proto3" json:"total,omitempty"`
	Event         string                                   `protobuf:"bytes,7,opt,name=event,proto3" json:"event,omitempty"`
	Status        string                                   `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Note          string                                   `protobuf:"bytes,9,opt,name=note,proto3" json:"note,omitempty"`
	User          *api.User                                `protobuf:"bytes,10,opt,name=user,proto3" json:"user,omitempty"`
	CreatedAt     *timestamppb.Timestamp                   `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp                   `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Serial        string                                   `protobuf:"bytes,13,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse_GetOrdersOrder) Reset() {
	*x = GetOrdersResponse_GetOrdersOrder{}
	mi := &file_orders_orders_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse_GetOrdersOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse_GetOrdersOrder) ProtoMessage() {}

func (x *GetOrdersResponse_GetOrdersOrder) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse_GetOrdersOrder.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse_GetOrdersOrder) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetOrdersResponse_GetOrdersOrder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder) GetItems() []*GetOrdersResponse_GetOrdersOrder_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetOrdersResponse_GetOrdersOrder) GetSubtotal() string {
	if x != nil {
		return x.Subtotal
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder) GetUser() *api.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetOrdersResponse_GetOrdersOrder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetOrdersResponse_GetOrdersOrder) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetOrdersResponse_GetOrdersOrder) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type GetOrdersResponse_GetOrdersOrder_ReturnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse_GetOrdersOrder_ReturnRequest) Reset() {
	*x = GetOrdersResponse_GetOrdersOrder_ReturnRequest{}
	mi := &file_orders_orders_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse_GetOrdersOrder_ReturnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse_GetOrdersOrder_ReturnRequest) ProtoMessage() {}

func (x *GetOrdersResponse_GetOrdersOrder_ReturnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse_GetOrdersOrder_ReturnRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse_GetOrdersOrder_ReturnRequest) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *GetOrdersResponse_GetOrdersOrder_ReturnRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder_ReturnRequest) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

type GetOrdersResponse_GetOrdersOrder_Item struct {
	state         protoimpl.MessageState                          `protogen:"open.v1"`
	TicketStock   string                                          `protobuf:"bytes,1,opt,name=ticket_stock,json=ticketStock,proto3" json:"ticket_stock,omitempty"`
	Session       string                                          `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Quantity      int64                                           `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         string                                          `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Name          string                                          `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                                          `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	ReturnRequest *GetOrdersResponse_GetOrdersOrder_ReturnRequest `protobuf:"bytes,7,opt,name=return_request,json=returnRequest,proto3" json:"return_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) Reset() {
	*x = GetOrdersResponse_GetOrdersOrder_Item{}
	mi := &file_orders_orders_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse_GetOrdersOrder_Item) ProtoMessage() {}

func (x *GetOrdersResponse_GetOrdersOrder_Item) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse_GetOrdersOrder_Item.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse_GetOrdersOrder_Item) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{4, 0, 1}
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) GetTicketStock() string {
	if x != nil {
		return x.TicketStock
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) GetReturnRequest() *GetOrdersResponse_GetOrdersOrder_ReturnRequest {
	if x != nil {
		return x.ReturnRequest
	}
	return nil
}

type GetUserOrdersResponse_GetOrdersOrder struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Id            string                                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Items         []*GetUserOrdersResponse_GetOrdersOrder_Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Total         string                                       `protobuf:"bytes,5,opt,name=total,proto3" json:"total,omitempty"`
	Event         string                                       `protobuf:"bytes,7,opt,name=event,proto3" json:"event,omitempty"`
	Status        string                                       `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp                       `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Serial        string                                       `protobuf:"bytes,12,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersResponse_GetOrdersOrder) Reset() {
	*x = GetUserOrdersResponse_GetOrdersOrder{}
	mi := &file_orders_orders_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersResponse_GetOrdersOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersResponse_GetOrdersOrder) ProtoMessage() {}

func (x *GetUserOrdersResponse_GetOrdersOrder) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersResponse_GetOrdersOrder.ProtoReflect.Descriptor instead.
func (*GetUserOrdersResponse_GetOrdersOrder) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GetUserOrdersResponse_GetOrdersOrder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserOrdersResponse_GetOrdersOrder) GetItems() []*GetUserOrdersResponse_GetOrdersOrder_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetUserOrdersResponse_GetOrdersOrder) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *GetUserOrdersResponse_GetOrdersOrder) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *GetUserOrdersResponse_GetOrdersOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetUserOrdersResponse_GetOrdersOrder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetUserOrdersResponse_GetOrdersOrder) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type GetUserOrdersResponse_GetOrdersOrder_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketStock   string                 `protobuf:"bytes,1,opt,name=ticket_stock,json=ticketStock,proto3" json:"ticket_stock,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersResponse_GetOrdersOrder_Item) Reset() {
	*x = GetUserOrdersResponse_GetOrdersOrder_Item{}
	mi := &file_orders_orders_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersResponse_GetOrdersOrder_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersResponse_GetOrdersOrder_Item) ProtoMessage() {}

func (x *GetUserOrdersResponse_GetOrdersOrder_Item) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersResponse_GetOrdersOrder_Item.ProtoReflect.Descriptor instead.
func (*GetUserOrdersResponse_GetOrdersOrder_Item) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{6, 0, 0}
}

func (x *GetUserOrdersResponse_GetOrdersOrder_Item) GetTicketStock() string {
	if x != nil {
		return x.TicketStock
	}
	return ""
}

func (x *GetUserOrdersResponse_GetOrdersOrder_Item) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *GetUserOrdersResponse_GetOrdersOrder_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GetUserOrdersResponse_GetOrdersOrder_Item) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetUserOrdersResponse_GetOrdersOrder_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetOrderResponse_Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subtotal      string                 `protobuf:"bytes,3,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Total         string                 `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`
	Event         string                 `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Note          string                 `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	User          *api.User              `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Serial        string                 `protobuf:"bytes,11,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse_Order) Reset() {
	*x = GetOrderResponse_Order{}
	mi := &file_orders_orders_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse_Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_Order) ProtoMessage() {}

func (x *GetOrderResponse_Order) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_Order.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_Order) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{13, 0}
}

func (x *GetOrderResponse_Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrderResponse_Order) GetSubtotal() string {
	if x != nil {
		return x.Subtotal
	}
	return ""
}

func (x *GetOrderResponse_Order) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *GetOrderResponse_Order) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *GetOrderResponse_Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderResponse_Order) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *GetOrderResponse_Order) GetUser() *api.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetOrderResponse_Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetOrderResponse_Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetOrderResponse_Order) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type GetOrderResponse_Item struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Id            string                               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketStock   string                               `protobuf:"bytes,2,opt,name=ticket_stock,json=ticketStock,proto3" json:"ticket_stock,omitempty"`
	Session       string                               `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	Quantity      int64                                `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         string                               `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Name          string                               `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                               `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ReturnRequest *GetOrderResponse_Item_ReturnRequest `protobuf:"bytes,8,opt,name=return_request,json=returnRequest,proto3" json:"return_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse_Item) Reset() {
	*x = GetOrderResponse_Item{}
	mi := &file_orders_orders_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_Item) ProtoMessage() {}

func (x *GetOrderResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_Item.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_Item) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{13, 1}
}

func (x *GetOrderResponse_Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrderResponse_Item) GetTicketStock() string {
	if x != nil {
		return x.TicketStock
	}
	return ""
}

func (x *GetOrderResponse_Item) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *GetOrderResponse_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GetOrderResponse_Item) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetOrderResponse_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetOrderResponse_Item) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderResponse_Item) GetReturnRequest() *GetOrderResponse_Item_ReturnRequest {
	if x != nil {
		return x.ReturnRequest
	}
	return nil
}

type GetOrderResponse_Bill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Payment       string                 `protobuf:"bytes,5,opt,name=payment,proto3" json:"payment,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse_Bill) Reset() {
	*x = GetOrderResponse_Bill{}
	mi := &file_orders_orders_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse_Bill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_Bill) ProtoMessage() {}

func (x *GetOrderResponse_Bill) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_Bill.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_Bill) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{13, 2}
}

func (x *GetOrderResponse_Bill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrderResponse_Bill) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *GetOrderResponse_Bill) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetOrderResponse_Bill) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderResponse_Bill) GetPayment() string {
	if x != nil {
		return x.Payment
	}
	return ""
}

func (x *GetOrderResponse_Bill) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetOrderResponse_Item_ReturnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse_Item_ReturnRequest) Reset() {
	*x = GetOrderResponse_Item_ReturnRequest{}
	mi := &file_orders_orders_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse_Item_ReturnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_Item_ReturnRequest) ProtoMessage() {}

func (x *GetOrderResponse_Item_ReturnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orders_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_Item_ReturnRequest.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_Item_ReturnRequest) Descriptor() ([]byte, []int) {
	return file_orders_orders_proto_rawDescGZIP(), []int{13, 1, 0}
}

func (x *GetOrderResponse_Item_ReturnRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GetOrderResponse_Item_ReturnRequest) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

var File_orders_orders_proto protoreflect.FileDescriptor

const file_orders_orders_proto_rawDesc = "" +
	"\n" +
	"\x13orders/orders.proto\x12\n" +
	"api.orders\x1a\fcommon.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x03\n" +
	"\x0fAddOrderRequest\x12@\n" +
	"\x05items\x18\x03 \x03(\v2 .api.orders.AddOrderRequest.ItemB\b\xbaH\x05\x92\x01\x02\b\x01R\x05items\x12#\n" +
	"\bsubtotal\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bsubtotal\x12\x1d\n" +
	"\x05total\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05total\x12\x1e\n" +
	"\x05event\x18\a \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05event\x12)\n" +
	"\vmerchant_id\x18\b \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\n" +
	"merchantId\x12P\n" +
	"\x0epayment_method\x18\t \x01(\v2).api.orders.AddOrderRequest.PaymentMethodR\rpaymentMethod\x1aM\n" +
	"\x04Item\x12 \n" +
	"\x06ticket\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x06ticket\x12#\n" +
	"\bquantity\x18\x02 \x01(\rB\a\xbaH\x04*\x02 \x00R\bquantity\x1aF\n" +
	"\rPaymentMethod\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04nameJ\x04\b\x01\x10\x02J\x04\b\x06\x10\aR\apaymentR\x04form\"F\n" +
	"\x10AddOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\abill_id\x18\x02 \x01(\tR\x06billId\"9\n" +
	"\x17IsEventHasOrdersRequest\x12\x1e\n" +
	"\x05event\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05event\"[\n" +
	"\x17GetOrdersByEventRequest\x12\x1e\n" +
	"\x05event\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05event\x12\x17\n" +
	"\x04page\x18\x02 \x01(\rH\x00R\x04page\x88\x01\x01B\a\n" +
	"\x05_page\"\x8c\a\n" +
	"\x11GetOrdersResponse\x12@\n" +
	"\x04data\x18\x01 \x03(\v2,.api.orders.GetOrdersResponse.GetOrdersOrderR\x04data\x12*\n" +
	"\tpage_info\x18\x02 \x01(\v2\r.api.PageInfoR\bpageInfo\x1a\x88\x06\n" +
	"\x0eGetOrdersOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12G\n" +
	"\x05items\x18\x03 \x03(\v21.api.orders.GetOrdersResponse.GetOrdersOrder.ItemR\x05items\x12\x1a\n" +
	"\bsubtotal\x18\x04 \x01(\tR\bsubtotal\x12\x14\n" +
	"\x05total\x18\x05 \x01(\tR\x05total\x12\x14\n" +
	"\x05event\x18\a \x01(\tR\x05event\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x12\n" +
	"\x04note\x18\t \x01(\tR\x04note\x12\x1d\n" +
	"\x04user\x18\n" +
	" \x01(\v2\t.api.UserR\x04user\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06serial\x18\r \x01(\tR\x06serial\x1af\n" +
	"\rReturnRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12=\n" +
	"\frequested_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\x1a\x84\x02\n" +
	"\x04Item\x12!\n" +
	"\fticket_stock\x18\x01 \x01(\tR\vticketStock\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12a\n" +
	"\x0ereturn_request\x18\a \x01(\v2:.api.orders.GetOrdersResponse.GetOrdersOrder.ReturnRequestR\rreturnRequestJ\x04\b\x02\x10\x03R\apayment\"a\n" +
	"\x19GetOrdersBySessionRequest\x12\"\n" +
	"\asession\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\asession\x12\x17\n" +
	"\x04page\x18\x02 \x01(\rH\x00R\x04page\x88\x01\x01B\a\n" +
	"\x05_page\"\x95\x04\n" +
	"\x15GetUserOrdersResponse\x12D\n" +
	"\x04data\x18\x01 \x03(\v20.api.orders.GetUserOrdersResponse.GetOrdersOrderR\x04data\x12\x14\n" +
	"\x05after\x18\x02 \x01(\tR\x05after\x1a\x9f\x03\n" +
	"\x0eGetOrdersOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12K\n" +
	"\x05items\x18\x03 \x03(\v25.api.orders.GetUserOrdersResponse.GetOrdersOrder.ItemR\x05items\x12\x14\n" +
	"\x05total\x18\x05 \x01(\tR\x05total\x12\x14\n" +
	"\x05event\x18\a \x01(\tR\x05event\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06serial\x18\f \x01(\tR\x06serial\x1a\x89\x01\n" +
	"\x04Item\x12!\n" +
	"\fticket_stock\x18\x01 \x01(\tR\vticketStock\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04nameJ\x04\b\x02\x10\x03R\apayment\";\n" +
	"\x14GetUserOrdersRequest\x12\x19\n" +
	"\x05after\x18\x01 \x01(\tH\x00R\x05after\x88\x01\x01B\b\n" +
	"\x06_after\"\xa9\x02\n" +
	"\x1cChangeOrderItemStatusRequest\x12\x1e\n" +
	"\x05order\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05order\x12\x1c\n" +
	"\x04item\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x04item\x12Z\n" +
	"\x06status\x18\x03 \x01(\x0e28.api.orders.ChangeOrderItemStatusRequest.OrderItemStatusB\b\xbaH\x05\x82\x01\x02\x10\x01R\x06status\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"W\n" +
	"\x0fOrderItemStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bCANCELED\x10\x01\x12\x14\n" +
	"\x10RETURN_REQUESTED\x10\x03\x12\x13\n" +
	"\x0fRETURN_APPROVED\x10\x04\"5\n" +
	"\x13GetOrderByIDRequest\x12\x1e\n" +
	"\x05order\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05order\"\\\n" +
	"\x12CancelOrderRequest\x12\x1e\n" +
	"\x05order\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05order\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"~\n" +
	"\x1dRequestOrderItemRefundRequest\x12\x1e\n" +
	"\x05order\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05order\x12\x1c\n" +
	"\x04item\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x04item\x12\x1f\n" +
	"\x06reason\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06reason\"}\n" +
	"\x1cRejectOrderItemRefundRequest\x12\x1e\n" +
	"\x05order\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05order\x12\x1c\n" +
	"\x04item\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x04item\x12\x1f\n" +
	"\x06reason\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06reason\"\xae\b\n" +
	"\x10GetOrderResponse\x128\n" +
	"\x05order\x18\x01 \x01(\v2\".api.orders.GetOrderResponse.OrderR\x05order\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.api.orders.GetOrderResponse.ItemR\x05items\x127\n" +
	"\x05bills\x18\x03 \x03(\v2!.api.orders.GetOrderResponse.BillR\x05bills\x1a\xc7\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bsubtotal\x18\x03 \x01(\tR\bsubtotal\x12\x14\n" +
	"\x05total\x18\x04 \x01(\tR\x05total\x12\x14\n" +
	"\x05event\x18\x05 \x01(\tR\x05event\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\x12\x1d\n" +
	"\x04user\x18\b \x01(\v2\t.api.UserR\x04user\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06serial\x18\v \x01(\tR\x06serialJ\x04\b\x02\x10\x03R\apayment\x1a\xf1\x02\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fticket_stock\x18\x02 \x01(\tR\vticketStock\x12\x18\n" +
	"\asession\x18\x03 \x01(\tR\asession\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\tR\x05price\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12V\n" +
	"\x0ereturn_request\x18\b \x01(\v2/.api.orders.GetOrderResponse.Item.ReturnRequestR\rreturnRequest\x1af\n" +
	"\rReturnRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12=\n" +
	"\frequested_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\x1a\xaf\x01\n" +
	"\x04Bill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\apayment\x18\x05 \x01(\tR\apayment\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xd4\x06\n" +
	"\x12OrdersAdminService\x12L\n" +
	"\x14IsEventHasOpenOrders\x12#.api.orders.IsEventHasOrdersRequest\x1a\r.api.Response\"\x00\x12u\n" +
	"\x10GetOrdersByEvent\x12#.api.orders.GetOrdersByEventRequest\x1a\r.api.Response\"-\x82\xd3\xe4\x93\x02'\x12%/api/v1/console/events/{event}/orders\x12}\n" +
	"\x12GetOrdersBySession\x12%.api.orders.GetOrdersBySessionRequest\x1a\r.api.Response\"1\x82\xd3\xe4\x93\x02+\x12)/api/v1/console/sessions/{session}/orders\x12\x88\x01\n" +
	"\x15ChangeOrderItemStatus\x12(.api.orders.ChangeOrderItemStatusRequest\x1a\r.api.Response\"6\x82\xd3\xe4\x93\x020:\x01*2+/api/v1/console/orders/{order}/items/{item}\x12f\n" +
	"\fGetOrderByID\x12\x1f.api.orders.GetOrderByIDRequest\x1a\r.api.Response\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/v1/console/orders/{order}\x12n\n" +
	"\vCancelOrder\x12\x1e.api.orders.CancelOrderRequest\x1a\r.api.Response\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/v1/console/orders/{order}:cancel\x12\x96\x01\n" +
	"\x15RejectOrderItemRefund\x12(.api.orders.RejectOrderItemRefundRequest\x1a\r.api.Response\"D\x82\xd3\xe4\x93\x02>:\x01*\"9/api/v1/console/orders/{order}/items/{item}:reject-refund2\xc6\x03\n" +
	"\fOrderService\x12X\n" +
	"\rGetUserOrders\x12 .api.orders.GetUserOrdersRequest\x1a\r.api.Response\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/orders\x12`\n" +
	"\bAddOrder\x12\x1b.api.orders.AddOrderRequest\x1a\r.api.Response\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/events/{event}/orders\x12f\n" +
	"\vCancelOrder\x12\x1e.api.orders.CancelOrderRequest\x1a\r.api.Response\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/orders/{order}:cancel\x12\x91\x01\n" +
	"\x16RequestOrderItemRefund\x12).api.orders.RequestOrderItemRefundRequest\x1a\r.api.Response\"=\x82\xd3\xe4\x93\x027:\x01*\"2/api/v1/orders/{order}/items/{item}:request-refundB\x1cZ\x1apartivo_tickets/api/ordersb\x06proto3"

var (
	file_orders_orders_proto_rawDescOnce sync.Once
	file_orders_orders_proto_rawDescData []byte
)

func file_orders_orders_proto_rawDescGZIP() []byte {
	file_orders_orders_proto_rawDescOnce.Do(func() {
		file_orders_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_orders_proto_rawDesc), len(file_orders_orders_proto_rawDesc)))
	})
	return file_orders_orders_proto_rawDescData
}

var file_orders_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orders_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_orders_orders_proto_goTypes = []any{
	(ChangeOrderItemStatusRequest_OrderItemStatus)(0),      // 0: api.orders.ChangeOrderItemStatusRequest.OrderItemStatus
	(*AddOrderRequest)(nil),                                // 1: api.orders.AddOrderRequest
	(*AddOrderResponse)(nil),                               // 2: api.orders.AddOrderResponse
	(*IsEventHasOrdersRequest)(nil),                        // 3: api.orders.IsEventHasOrdersRequest
	(*GetOrdersByEventRequest)(nil),                        // 4: api.orders.GetOrdersByEventRequest
	(*GetOrdersResponse)(nil),                              // 5: api.orders.GetOrdersResponse
	(*GetOrdersBySessionRequest)(nil),                      // 6: api.orders.GetOrdersBySessionRequest
	(*GetUserOrdersResponse)(nil),                          // 7: api.orders.GetUserOrdersResponse
	(*GetUserOrdersRequest)(nil),                           // 8: api.orders.GetUserOrdersRequest
	(*ChangeOrderItemStatusRequest)(nil),                   // 9: api.orders.ChangeOrderItemStatusRequest
	(*GetOrderByIDRequest)(nil),                            // 10: api.orders.GetOrderByIDRequest
	(*CancelOrderRequest)(nil),                             // 11: api.orders.CancelOrderRequest
	(*RequestOrderItemRefundRequest)(nil),                  // 12: api.orders.RequestOrderItemRefundRequest
	(*RejectOrderItemRefundRequest)(nil),                   // 13: api.orders.RejectOrderItemRefundRequest
	(*GetOrderResponse)(nil),                               // 14: api.orders.GetOrderResponse
	(*AddOrderRequest_Item)(nil),                           // 15: api.orders.AddOrderRequest.Item
	(*AddOrderRequest_PaymentMethod)(nil),                  // 16: api.orders.AddOrderRequest.PaymentMethod
	(*GetOrdersResponse_GetOrdersOrder)(nil),               // 17: api.orders.GetOrdersResponse.GetOrdersOrder
	(*GetOrdersResponse_GetOrdersOrder_ReturnRequest)(nil), // 18: api.orders.GetOrdersResponse.GetOrdersOrder.ReturnRequest
	(*GetOrdersResponse_GetOrdersOrder_Item)(nil),          // 19: api.orders.GetOrdersResponse.GetOrdersOrder.Item
	(*GetUserOrdersResponse_GetOrdersOrder)(nil),           // 20: api.orders.GetUserOrdersResponse.GetOrdersOrder
	(*GetUserOrdersResponse_GetOrdersOrder_Item)(nil),      // 21: api.orders.GetUserOrdersResponse.GetOrdersOrder.Item
	(*GetOrderResponse_Order)(nil),                         // 22: api.orders.GetOrderResponse.Order
	(*GetOrderResponse_Item)(nil),                          // 23: api.orders.GetOrderResponse.Item
	(*GetOrderResponse_Bill)(nil),                          // 24: api.orders.GetOrderResponse.Bill
	(*GetOrderResponse_Item_ReturnRequest)(nil),            // 25: api.orders.GetOrderResponse.Item.ReturnRequest
	(*api.PageInfo)(nil),                                   // 26: api.PageInfo
	(*api.User)(nil),                                       // 27: api.User
	(*timestamppb.Timestamp)(nil),                          // 28: google.protobuf.Timestamp
	(*api.Response)(nil),                                   // 29: api.Response
}
var file_orders_orders_proto_depIdxs = []int32{
	15, // 0: api.orders.AddOrderRequest.items:type_name -> api.orders.AddOrderRequest.Item
	16, // 1: api.orders.AddOrderRequest.payment_method:type_name -> api.orders.AddOrderRequest.PaymentMethod
	17, // 2: api.orders.GetOrdersResponse.data:type_name -> api.orders.GetOrdersResponse.GetOrdersOrder
	26, // 3: api.orders.GetOrdersResponse.page_info:type_name -> api.PageInfo
	20, // 4: api.orders.GetUserOrdersResponse.data:type_name -> api.orders.GetUserOrdersResponse.GetOrdersOrder
	0,  // 5: api.orders.ChangeOrderItemStatusRequest.status:type_name -> api.orders.ChangeOrderItemStatusRequest.OrderItemStatus
	22, // 6: api.orders.GetOrderResponse.order:type_name -> api.orders.GetOrderResponse.Order
	23, // 7: api.orders.GetOrderResponse.items:type_name -> api.orders.GetOrderResponse.Item
	24, // 8: api.orders.GetOrderResponse.bills:type_name -> api.orders.GetOrderResponse.Bill
	19, // 9: api.orders.GetOrdersResponse.GetOrdersOrder.items:type_name -> api.orders.GetOrdersResponse.GetOrdersOrder.Item
	27, // 10: api.orders.GetOrdersResponse.GetOrdersOrder.user:type_name -> api.User
	28, // 11: api.orders.GetOrdersResponse.GetOrdersOrder.created_at:type_name -> google.protobuf.Timestamp
	28, // 12: api.orders.GetOrdersResponse.GetOrdersOrder.updated_at:type_name -> google.protobuf.Timestamp
	28, // 13: api.orders.GetOrdersResponse.GetOrdersOrder.ReturnRequest.requested_at:type_name -> google.protobuf.Timestamp
	18, // 14: api.orders.GetOrdersResponse.GetOrdersOrder.Item.return_request:type_name -> api.orders.GetOrdersResponse.GetOrdersOrder.ReturnRequest
	21, // 15: api.orders.GetUserOrdersResponse.GetOrdersOrder.items:type_name -> api.orders.GetUserOrdersResponse.GetOrdersOrder.Item
	28, // 16: api.orders.GetUserOrdersResponse.GetOrdersOrder.created_at:type_name -> google.protobuf.Timestamp
	27, // 17: api.orders.GetOrderResponse.Order.user:type_name -> api.User
	28, // 18: api.orders.GetOrderResponse.Order.created_at:type_name -> google.protobuf.Timestamp
	28, // 19: api.orders.GetOrderResponse.Order.updated_at:type_name -> google.protobuf.Timestamp
	25, // 20: api.orders.GetOrderResponse.Item.return_request:type_name -> api.orders.GetOrderResponse.Item.ReturnRequest
	28, // 21: api.orders.GetOrderResponse.Bill.created_at:type_name -> google.protobuf.Timestamp
	28, // 22: api.orders.GetOrderResponse.Item.ReturnRequest.requested_at:type_name -> google.protobuf.Timestamp
	3,  // 23: api.orders.OrdersAdminService.IsEventHasOpenOrders:input_type -> api.orders.IsEventHasOrdersRequest
	4,  // 24: api.orders.OrdersAdminService.GetOrdersByEvent:input_type -> api.orders.GetOrdersByEventRequest
	6,  // 25: api.orders.OrdersAdminService.GetOrdersBySession:input_type -> api.orders.GetOrdersBySessionRequest
	9,  // 26: api.orders.OrdersAdminService.ChangeOrderItemStatus:input_type -> api.orders.ChangeOrderItemStatusRequest
	10, // 27: api.orders.OrdersAdminService.GetOrderByID:input_type -> api.orders.GetOrderByIDRequest
	11, // 28: api.orders.OrdersAdminService.CancelOrder:input_type -> api.orders.CancelOrderRequest
	13, // 29: api.orders.OrdersAdminService.RejectOrderItemRefund:input_type -> api.orders.RejectOrderItemRefundRequest
	8,  // 30: api.orders.OrderService.GetUserOrders:input_type -> api.orders.GetUserOrdersRequest
	1,  // 31: api.orders.OrderService.AddOrder:input_type -> api.orders.AddOrderRequest
	11, // 32: api.orders.OrderService.CancelOrder:input_type -> api.orders.CancelOrderRequest
	12, // 33: api.orders.OrderService.RequestOrderItemRefund:input_type -> api.orders.RequestOrderItemRefundRequest
	29, // 34: api.orders.OrdersAdminService.IsEventHasOpenOrders:output_type -> api.Response
	29, // 35: api.orders.OrdersAdminService.GetOrdersByEvent:output_type -> api.Response
	29, // 36: api.orders.OrdersAdminService.GetOrdersBySession:output_type -> api.Response
	29, // 37: api.orders.OrdersAdminService.ChangeOrderItemStatus:output_type -> api.Response
	29, // 38: api.orders.OrdersAdminService.GetOrderByID:output_type -> api.Response
	29, // 39: api.orders.OrdersAdminService.CancelOrder:output_type -> api.Response
	29, // 40: api.orders.OrdersAdminService.RejectOrderItemRefund:output_type -> api.Response
	29, // 41: api.orders.OrderService.GetUserOrders:output_type -> api.Response
	29, // 42: api.orders.OrderService.AddOrder:output_type -> api.Response
	29, // 43: api.orders.OrderService.CancelOrder:output_type -> api.Response
	29, // 44: api.orders.OrderService.RequestOrderItemRefund:output_type -> api.Response
	34, // [34:45] is the sub-list for method output_type
	23, // [23:34] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_orders_orders_proto_init() }
func file_orders_orders_proto_init() {
	if File_orders_orders_proto != nil {
		return
	}
	file_orders_orders_proto_msgTypes[3].OneofWrappers = []any{}
	file_orders_orders_proto_msgTypes[5].OneofWrappers = []any{}
	file_orders_orders_proto_msgTypes[7].OneofWrappers = []any{}
	file_orders_orders_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_orders_proto_rawDesc), len(file_orders_orders_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_orders_orders_proto_goTypes,
		DependencyIndexes: file_orders_orders_proto_depIdxs,
		EnumInfos:         file_orders_orders_proto_enumTypes,
		MessageInfos:      file_orders_orders_proto_msgTypes,
	}.Build()
	File_orders_orders_proto = out.File
	file_orders_orders_proto_goTypes = nil
	file_orders_orders_proto_depIdxs = nil
}
