// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"partivo_tickets/internal/app"
	"partivo_tickets/internal/conf"
	"partivo_tickets/internal/dao/mongodb"
	"partivo_tickets/internal/dao/repository"
	"partivo_tickets/internal/limiter"
	"partivo_tickets/internal/logger"
	"partivo_tickets/internal/logic"
	"partivo_tickets/internal/middleware/http"
	"partivo_tickets/internal/mq"
	"partivo_tickets/internal/mq/rabbitmq"
	"partivo_tickets/internal/provider"
	"partivo_tickets/internal/service"
	"partivo_tickets/internal/worker"
	"partivo_tickets/pkg/snowflake"
)

// Injectors from wire.go:

func InitializeFrontendApp(appConfig *conf.AppConfig) (*app.App, func(), error) {
	int2 := appConfig.Port
	logConfig := appConfig.LogConfig
	appMode := provider.ProvideAppMode(appConfig)
	zapLogger, err := logger.NewLogger(logConfig, appMode)
	if err != nil {
		return nil, nil, err
	}
	mongodbConfig := appConfig.MongodbConfig
	client, cleanup, err := mongodb.NewMongoDB(mongodbConfig)
	if err != nil {
		return nil, nil, err
	}
	database := provider.ProvideDatabase(client, mongodbConfig)
	ticketsDAO := mongodb.NewTicketsDAO(database, zapLogger)
	ordersDAO := mongodb.NewOrdersDAO(database, zapLogger)
	auditLogDAO := mongodb.NewAuditLogDAO(database, zapLogger)
	relationClient, cleanup2, err := provider.ProvideRelationClient(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	manager, err := provider.ProvideJwtGenerator(appConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	eventsClient, cleanup3, err := provider.ProvideEventsClient(appConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	outboxDAO := mongodb.NewOutboxDAO(client, mongodbConfig)
	generateTicketsTopic := provider.ProvideGenerateTicketsTopic(appConfig)
	ticketEventPublisher := logic.NewTicketEventPublisher(outboxDAO, generateTicketsTopic)
	ticketLogic := logic.NewTicketLogic(ticketsDAO, ordersDAO, auditLogDAO, relationClient, zapLogger, manager, eventsClient, ticketEventPublisher)
	ticketsService := service.NewTicketsService(ticketLogic, appConfig, zapLogger)
	billDAO := mongodb.NewBillDAO(database, zapLogger)
	paymentEventTopic := provider.ProvidePaymentEventTopic(appConfig)
	paymentEventPublisher := logic.NewPaymentEventPublisher(outboxDAO, paymentEventTopic)
	uint16_2 := provider.ProvideMachineID()
	generator, err := snowflake.NewGenerator(uint16_2)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	orderLogic := logic.NewOrderLogic(ordersDAO, billDAO, ticketsDAO, auditLogDAO, paymentEventPublisher, relationClient, generator, zapLogger)
	transactionManager := provider.ProvideTransactionManager(appMode, client)
	orderService := service.NewOrderService(orderLogic, zapLogger, transactionManager)
	billLogic := logic.NewBillLogic(billDAO, ordersDAO, auditLogDAO, paymentEventPublisher, zapLogger, relationClient)
	billService := service.NewBillService(billLogic, zapLogger)
	v := provideFrontendServices(ticketsService, orderService, billService)
	httpHandlerRegister := provideNilHttpHandlerRegister()
	v2 := conf.NewUnaryInterceptors()
	v3 := conf.NewAllowedHeaders()
	v4 := provideFrontendWorkers()
	appApp, cleanup4, err := app.NewApp(int2, zapLogger, v, httpHandlerRegister, v2, v3, v4)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return appApp, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

func InitializeConsoleApp(appConfig *conf.AppConfig) (*app.App, func(), error) {
	int2 := appConfig.Port
	logConfig := appConfig.LogConfig
	appMode := provider.ProvideAppMode(appConfig)
	zapLogger, err := logger.NewLogger(logConfig, appMode)
	if err != nil {
		return nil, nil, err
	}
	mongodbConfig := appConfig.MongodbConfig
	client, cleanup, err := mongodb.NewMongoDB(mongodbConfig)
	if err != nil {
		return nil, nil, err
	}
	database := provider.ProvideDatabase(client, mongodbConfig)
	ordersDAO := mongodb.NewOrdersDAO(database, zapLogger)
	billDAO := mongodb.NewBillDAO(database, zapLogger)
	ticketsDAO := mongodb.NewTicketsDAO(database, zapLogger)
	auditLogDAO := mongodb.NewAuditLogDAO(database, zapLogger)
	outboxDAO := mongodb.NewOutboxDAO(client, mongodbConfig)
	paymentEventTopic := provider.ProvidePaymentEventTopic(appConfig)
	paymentEventPublisher := logic.NewPaymentEventPublisher(outboxDAO, paymentEventTopic)
	relationClient, cleanup2, err := provider.ProvideRelationClient(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	uint16_2 := provider.ProvideMachineID()
	generator, err := snowflake.NewGenerator(uint16_2)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	orderLogic := logic.NewOrderLogic(ordersDAO, billDAO, ticketsDAO, auditLogDAO, paymentEventPublisher, relationClient, generator, zapLogger)
	transactionManager := provider.ProvideTransactionManager(appMode, client)
	ordersAdminService := service.NewOrdersAdminService(orderLogic, zapLogger, transactionManager)
	manager, err := provider.ProvideJwtGenerator(appConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	eventsClient, cleanup3, err := provider.ProvideEventsClient(appConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	generateTicketsTopic := provider.ProvideGenerateTicketsTopic(appConfig)
	ticketEventPublisher := logic.NewTicketEventPublisher(outboxDAO, generateTicketsTopic)
	ticketLogic := logic.NewTicketLogic(ticketsDAO, ordersDAO, auditLogDAO, relationClient, zapLogger, manager, eventsClient, ticketEventPublisher)
	ticketsAdminService := service.NewTicketsAdminService(ticketLogic, zapLogger, transactionManager, manager)
	billLogic := logic.NewBillLogic(billDAO, ordersDAO, auditLogDAO, paymentEventPublisher, zapLogger, relationClient)
	billsAdminService := service.NewBillsAdminService(billLogic, orderLogic, zapLogger, transactionManager)
	v := provideConsoleServices(ordersAdminService, ticketsAdminService, billsAdminService)
	authMiddleware := http.NewAuthMiddleware()
	rateLimiterConfig := appConfig.RateLimiterConfig
	redisConfig := appConfig.RedisConfig
	redisClient, cleanup4, err := provider.ProvideRedisClient(redisConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	redisNamespace := provider.ProvideRedisNamespace(appConfig)
	limiterManager, err := limiter.NewManager(rateLimiterConfig, redisClient, redisNamespace)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	orderExportHandler := service.NewOrderExportHandler(orderLogic)
	httpHandlerRegister := app.NewHttpHandlerRegister(authMiddleware, limiterManager, orderExportHandler)
	v2 := conf.NewUnaryInterceptors()
	v3 := conf.NewAllowedHeaders()
	rabbitMQConfig := appConfig.RabbitMQConfig
	publisher, err := rabbitmq.NewPublisher(rabbitMQConfig, zapLogger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	workerConfig := appConfig.WorkerConfig
	outboxProcessor := worker.NewOutboxProcessor(outboxDAO, publisher, zapLogger, workerConfig)
	v4 := provideConsoleWorkers(outboxProcessor)
	appApp, cleanup5, err := app.NewApp(int2, zapLogger, v, httpHandlerRegister, v2, v3, v4)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return appApp, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// baseProviders 包含所有應用共用的基礎元件 (不含 MQ)
var baseProviders = wire.NewSet(wire.FieldsOf(new(*conf.AppConfig), "LogConfig", "MongodbConfig", "KetoConfig", "WorkerConfig", "EventServiceConfig", "JwtConfig", "RedisConfig", "RateLimiterConfig"), provider.ProvideAppMode, logger.NewLogger, mongodb.NewMongoDB, provider.ProvideDatabase, provider.ProvideRelationClient, provider.ProvideMachineID, provider.ProvideGenerateTicketsTopic, provider.ProvidePaymentEventTopic, provider.ProvideTransactionManager, provider.ProvideJwtGenerator, provider.ProvideEventsClient, provider.ProvideRedisNamespace, provider.ProvideRedisClient, limiter.NewManager, snowflake.NewGenerator, mongodb.NewTicketsDAO, wire.Bind(new(repository.TicketsRepository), new(*mongodb.TicketsDAO)), mongodb.NewOrdersDAO, wire.Bind(new(repository.OrdersRepository), new(*mongodb.OrdersDAO)), mongodb.NewBillDAO, wire.Bind(new(repository.BillRepository), new(*mongodb.BillDAO)), mongodb.NewAuditLogDAO, wire.Bind(new(repository.AuditLogRepository), new(*mongodb.AuditLogDAO)), mongodb.NewOutboxDAO, wire.Bind(new(repository.OutboxRepository), new(*mongodb.OutboxDAO)), logic.NewPaymentEventPublisher, logic.NewTicketEventPublisher, logic.NewTicketLogic, logic.OrderLogicProviderSet, logic.NewBillLogic)

// rabbitMQProviders 包含 RabbitMQ 的 Publisher 和 Worker
var rabbitMQProviders = wire.NewSet(wire.FieldsOf(new(*conf.AppConfig), "RabbitMQConfig"), rabbitmq.NewPublisher, wire.Bind(new(mq.Publisher), new(*rabbitmq.Publisher)), worker.NewOutboxProcessor)

func provideFrontendServices(ticketService *service.TicketsService, orderService *service.OrderService, billService *service.BillService) []interface{} {
	return []interface{}{ticketService, orderService, billService}
}

// provideFrontendWorkers 為前端應用提供一個空的 Worker 切片
func provideFrontendWorkers() []worker.Worker {
	return []worker.Worker{}
}

// provideNilHttpHandlerRegister provides a nil register for apps that don't have custom handlers.
func provideNilHttpHandlerRegister() app.HttpHandlerRegister {
	return nil
}

func provideConsoleServices(
	ordersAdminService *service.OrdersAdminService,
	ticketsAdminService *service.TicketsAdminService,
	billsAdminService *service.BillsAdminService,
) []interface{} {
	return []interface{}{ordersAdminService, ticketsAdminService, billsAdminService}
}

// provideConsoleWorkers 將 OutboxProcessor 包裝成 Worker 切片
func provideConsoleWorkers(p *worker.OutboxProcessor) []worker.Worker {
	return []worker.Worker{p}
}
